### ISSUE TITLE
conduit-extra 1.1.4 test suite failure

### ISSUE THREAD

**Issue by peti** [snoyberg/conduit#177]
Build log is at <http://hydra.cryp.to/build/197919/nixlog/83/raw>.

**Comment by snoyberg** [comment]
@peti Is this still occurring? I've never received a test failure from stackage for conduit-extra.

**Comment by peti** [comment]
I don't know ... we don't run the test suite anymore.

**Comment by snoyberg** [comment]
It seems to be working for me now, so closing. If you turn on the test suite again and find failures, let me know.
