### ISSUE TITLE
split function for Data.Conduit.Text

### ISSUE THREAD

**Issue by MaxGabriel** [snoyberg/conduit#205]
Hi, I needed a split function for some log parsing I was doing with Conduit, would you be interested in me adding this to `Data.Conduit.Text`? If so, I can add tests and remove the Safe dependency that my code is using, then submit a PR.

This is the code I'm currently using; it's modeled closely after `lines` and I believe `lines` could be implemented in terms of `split`.

```haskell
split :: Monad m => Text -> Conduit Text m Text
split splitText = awaitText T.empty
    where
      awaitText buf = await >>= maybe (finish buf) (process buf)

      finish buf = unless (T.null buf) (yield buf)

      process buf text = yieldSplits $ buf `T.append` text

      yieldSplits text = do
        let splits = T.splitOn splitText text
            lastSplit = lastDef T.empty splits
        mapM_ yield (initSafe splits)
        awaitText lastSplit
```

**Comment by mgsloan** [comment]
I did something similar when implementing fusion in conduit-combinators: https://github.com/fpco/conduit-combinators/blob/master/Data/Conduit/Combinators.hs#L1889

The main difference is that yours takes a `Text` rather than `Element  seq -> Bool`.

**Comment by MaxGabriel** [comment]
Cool @mgsloan. I guess the conduit-combinators version of this would take an `EqSequence` and split its input using that?

**Comment by mgsloan** [comment]
Yup, that seems reasonable to me.  I'm not seeing an implementation of `split` for `EqSequence`, though.

**Comment by snoyberg** [comment]
I think the code above is subtly broken; if the broken-upon string occurs over a chunk boundary, it won't fire. E.g.:

```haskell
mapM_ yield ["123x", "x456"] $= split "xx"
```

doesn't look like it would result in the output you'd expect.

**Comment by snoyberg** [comment]
Tracked by PR #207
