### ISSUE TITLE
Duplicate test in Data.Conduit.TextSpec

### ISSUE THREAD

**Issue by MaxGabriel** [snoyberg/conduit#206]
The following test is repeated twice in `Data.Conduit.TextSpec`, once on [lines 186–188](https://github.com/snoyberg/conduit/blob/8be231dc5e64600bd2b0a966e525b7fe47c216a3/conduit-extra/test/Data/Conduit/TextSpec.hs#L186-L188) and then again on [lines 215–217](https://github.com/snoyberg/conduit/blob/8be231dc5e64600bd2b0a966e525b7fe47c216a3/conduit-extra/test/Data/Conduit/TextSpec.hs#L215-L217):

```haskell
it "is not too eager" $ do
    x <- CL.sourceList ["foobarbaz", error "ignore me"] C.$$ CT.decode CT.utf8 C.=$ CL.head
    x `shouldBe` Just "foobarbaz"
```

Suspiciously, the first function is grouped under the "text lines" describe block and the second is grouped under "text lines bounded", but the test doesn't call either of those functions. Maybe it was meant to be in the ["text decode" section](https://github.com/snoyberg/conduit/blob/8be231dc5e64600bd2b0a966e525b7fe47c216a3/conduit-extra/test/Data/Conduit/TextSpec.hs#L224)?

**Comment by snoyberg** [comment]
Good catch, looks like something that may have been a bad merge. Anyway, solution is simple enough, thanks!
