### ISSUE TITLE
Why is ResourceT not an instance of MonadResource?

### ISSUE THREAD

**Issue by pharpend** [snoyberg/conduit#215]
Is there a code reason? Or has it just not occured to anyone yet? It seems like the instance would be pretty simple:

```haskell
instance (Monad m) => MonadResource (ResourceT m) where
  liftResourceT = id
```

**Comment by snoyberg** [comment]
The instance does exist, just with a few more constraints:

https://github.com/snoyberg/conduit/blob/master/resourcet/Control/Monad/Trans/Resource/Internal.hs#L162

**Comment by pharpend** [comment]
Ah, okay! My skimming of the Hackage documentation didn't catch that. Thank you!
