### ISSUE TITLE
Parallelism with conduit

### ISSUE THREAD

**Issue by gibiansky** [snoyberg/conduit#223]
Is there a good helper library for parallelism with conduit?

For example, I'd like a parallel `mapM` sink, which performs an action on each incoming bit of data using a pool of worker threads. Does something like this exist? (I have several similar other needs as well.)

I have a "toy" implementation here; I say toy because I have not thought about resource usage, cleanup, or exception handling at all:
```haskell
{-# LANGUAGE RankNTypes #-}
module Data.Conduit.Parallel (parallelSink) where

import Control.Monad
import Control.Monad.IO.Class
import Control.Concurrent

import Control.Concurrent.STM

import Data.Conduit

-- So that threads know when to stop taking more work.
data More a = More a | Done

-- | Parallelize an effectful sink.
parallelSink :: MonadIO m => Int -> (a -> IO ()) -> Consumer a m ()
parallelSink threads f = do
  -- Create a new bounded channel.
  q <- liftIO $ newTBQueueIO threads

  -- Create signaling marker MVars for when the worker threads are done.
  threadMVars <- liftIO $ replicateM threads (atomically newEmptyTMVar)

  -- Make the worker threads.
  liftIO $ forM_ threadMVars $ \var ->
    let go = do
               next <- atomically $ readTBQueue q
               case next of
                 Done -> atomically $ putTMVar var ()
                 More val -> f val >> go
    in forkIO go

  -- Stream all values into the channel.
  awaitForever $ liftIO . atomically . writeTBQueue q . More

  liftIO $ do
    -- Tell all threads to stop.
    replicateM threads $ atomically . writeTBQueue q $ Done

    -- Now make sure all threads are done (wait on them)
    mapM_ (atomically . takeTMVar) threadMVars
```

If this does not yet exist, would there be any interest in getting a few such helper functions into `conduit-extra` or something?

**Comment by snoyberg** [comment]
I haven't used it in a while, but does [stm-conduit](http://www.stackage.org/package/stm-conduit) fit the bill?

**Comment by gibiansky** [comment]
Yes, that fits the bill. It seemed too complex for my use case the first time I looked at it, but upon reading the documentation a bit more thoroughly, it seems fairly reasonable. Thanks!
