### ISSUE TITLE
sourceCmdWithConsumer needs threaded runtime

### ISSUE THREAD

**Issue by erikd** [snoyberg/conduit#224]
I keep on getting caught out with this. I have a bunch of little programs (as source code) all over the place that use `sourceCmdWithConsumer`. 

The work fine under GHCi, but ocassionally I compile one of the and forget to compile with `-threaded` resulting in a program that hangs and does nothing.

What do you think of the idea of `sourceCmdWithConsumer`.  checking that `Control.Concurrent.rtsSupportsBoundThreads` is `True` and throwing an error if its not? In the case where it a program has not been compiled with the threaded runtime we now get an error which is infinitely better than an un-explained hang.

Thoughts?

**Comment by erikd** [comment]
Would be nicer if this could be a compiler (or rather linker) error.

**Comment by snoyberg** [comment]
1. What's the runtime overhead of adding that check?
2. Is it true that the call will always hang at runtime? I was under the impression that on some OSes it will succeed with the singlethreaded runtime.

Given the possibility of (2), and especially the possibility of that behavior changing in the future, I'm hesitant to encode this as a runtime error.

**Comment by erikd** [comment]
1) The runtime overhad is very low. Every call to `sourceCmdWithConsumer` would have the check the `Bool` value Control.Concurrent.rtsSupportsBoundThreads for `True` but it would have to do it every single time `sourceCmdWithConsumer` I called. In comparison to everything else `sourceCmnWIthCosumer` has to do, this check is effectively negligible.

2) It certainly hangs on Linux. On Monday, I'll test on other OSes and if other OSes don't need this test, a bit of CPP goop should sort it out.

**Comment by erikd** [comment]
Hmm, not all programs run with `sourceCmdWithConsumer` hang with the single threaded runtime.

It seems to be dependent on the length of the output, ie it doesn't hang for short outputs and does for long ones. I suspect that for the shorter outputs the data fits in a single `ByteString`.

**Comment by erikd** [comment]
Interestingly, the point where it switches over from not hanging to hanging is at 64 kilobytes. I could not find a constant like that anywhere in the conduit sources so I suspect it may be in Bytestring.

My test program looks like:

```haskell
import Control.Concurrent (rtsSupportsBoundThreads)
import Control.Monad.Logger (runStderrLoggingT)
import Data.Conduit
import Data.Conduit.Process

import qualified Data.ByteString.Char8 as BS
import qualified Data.Conduit.List as DC

main :: IO ()
main = do
    putStrLn $ "Threaded runtime : " ++ show rtsSupportsBoundThreads
    (ec, count) <- runStderrLoggingT $
                    sourceCmdWithConsumer "cat test.txt"
                    (toConsumer $ DC.fold (\ acc bs -> acc + BS.length bs) (0 ::Int))
    putStrLn $ "Read " ++ show count ++ " bytes."
    print ec
```

All it needs is a file named `test.txt`.

**Comment by erikd** [comment]
I can now confirm that ghc 7.8.3 on OSX hangs just like Linux.

**Comment by dminuoso** [comment]
We should perhaps just document it in haddock? This seems like minimal effort, and would tell users clearly what to enable if they want to use that feature.

**Comment by snoyberg** [comment]
Sounds great, PR welcome
