### ISSUE TITLE
Conduit README.md  -- make current?

### ISSUE THREAD

**Issue by haskellGardener** [snoyberg/conduit#226]
Should the README.md be updated to encourage the use of Data.Conduit.Combinators replacing the older CL?

Should the Unified data type section to more closely resemble the source type variable names of ConduitM i o m r , rather than Conduit a b m r?

**Comment by snoyberg** [comment]
I'm in favor of changes for the latter, PR welcome.

I'm not certain about combinators. Mentioning it in the readme is fine, but many people starting with conduit aren't going to want to install such a heavy weight dependency right off the bat.

**Comment by haskellGardener** [comment]
Cool.
