### ISSUE TITLE
Socks client support for Data.Conduit.Network

### ISSUE THREAD

**Issue by erikd** [snoyberg/conduit#228]
I need something like `runTCPClient` but connecting via a Socks proxy.

I've got some un-tested (it compiles, it may even work) code that has an API like:

```!hs
data SocksClientSettings = SocksClientSettings
    { socksClientHost :: !ByteString
    , socksClientPort :: !Int
    , socksDestHost :: !ByteString
    , socksDestPort :: !Int
    }


runTCPSocksClient :: SocksClientSettings -> (AppData -> IO a) -> IO a
```

The only additional module required to implement this is `Network.Socks5` by @vincenthz.

Is this something you would accept for the conduit-extra package, maybe in its own module like `Data.Conduit.Network.Socks5`?

**Comment by snoyberg** [comment]
I think I'd prefer this to go into a separate package.

**Comment by erikd** [comment]
Ok. For now I'll just keep it as module within the project I'm working on. If anyone asks you about this, point them in my direction and I'll actually do the work of packaging it.
