### ISSUE TITLE
Inconsistent void dependency

### ISSUE THREAD

**Issue by peti** [snoyberg/conduit#230]
The `conduit` library depends on `void` only when built with `ghc` < 7.9, but the test suite depends on `void` unconditionally, which feels odd. Is there a reason for this seemingly inconsistent spec?

**Comment by snoyberg** [comment]
No, not really, just laziness. I'm afk for the next two days, but if toy
could send a PR, I'll be able to merge it.

**Comment by peti** [comment]
Fixed in https://github.com/snoyberg/conduit/commit/f1e097c91bcdbf0f6cc4aa9f6b2ec61c197231a0.
