### ISSUE TITLE
conduit-1.2.5.1 build failures on GHC < 7.4 due to -XSafe

### ISSUE THREAD

**Issue by bergmark** [snoyberg/conduit#232]
GHC-7.0:
```
Data/Conduit.hs:3:14: Unsupported extension: Safe
```
GHC-7.2: 
```
Data/Conduit/Lift.hs:71:1:
    mmorph-1.0.4:Control.Monad.Morph can't be safely imported! The module itself isn't safe.
```

I know Edward Kmett has has lots of problems with safe inference in 7.2 so dunno if it's worth the effort. Should conduit have a `base >= 4.4` (or `>= 4.5`) lower bound? Or CPP the `Safe` pragmas?

I revised 1.2.5.1: https://hackage.haskell.org/package/conduit-1.2.5.1/revisions/

**Comment by snoyberg** [comment]
Thanks, I've added a 4.5 lower bound to base. I'm tempted to remove the
Safe pragmas entirely to be honest.
