### ISSUE TITLE
network-conduit-tls: resource vanished (Broken pipe) after successful communication.

### ISSUE THREAD

**Issue by gromakovsky** [snoyberg/conduit#236]
I have client and server which communicate via JSON values. Client sends some values to server, server reads them and sends response to client. Everything is fine, however after my callback (which i pass to runTLSClient) is finished there is an exception:

    <socket: 12>: hPutBuf: resource vanished (Broken pipe)

If I use Data.Conduit.Network (no TLS, simply TCP), then everything is fine.
I've written a very simple example which reproduces this problem (actually I used main.hs from network-conduit-tls/test and changed some logic): http://pastebin.com/vAm8ZK3n

In brief, there is a server which reads the first JSON value and sends it back and a client which simply sends "Test" to server.

Running it I get the following:

```
Values: ["\"Test\""]
Res with TLS: Left <socket: 12>: hPutBuf: resource vanished (Broken pipe)
Values: ["\"Test\""]
Res without TLS: Right ()
```

which shows that problem is only with TLS.

I'm not sure whether I am doing something wrong or there is real issue somewhere. Anyway, I will be really glad to get some help.

**Comment by snoyberg** [comment]
I just ran this with LTS 9.9, and got the output:

```
Values: ["\"Test\""]
Res with TLS: Right ()
Values: ["\"Test\""]
Res without TLS: Right ()
```

It looks like this bug may have been fixed already. Can you confirm that it's working for you too?

**Comment by gromakovsky** [comment]
With modern LTS I also can't reproduce it. So I think it indeed has been fixed. Sorry for disturbance.
