### ISSUE TITLE
Data.Conduit.Binary.lines only breaks on LF, not on CRLF

### ISSUE THREAD

**Issue by kqr** [snoyberg/conduit#240]
Many network protocols (at least HTTP and IRC) specify CRLF line endings (for God knows what reason) which makes breaking received bytestrings into "lines" on CRLF a very useful operation. I see that the existing `lines` function only breaks on LF.

Ideally, in my mind, `lines` would detect if there's a trailing CR after breaking on the LF, and then remove that too from the return value. I'm just curious if there's a reason it's not that way now, or if the reason is just "nobody has been bothered to do it yet".

**Comment by snoyberg** [comment]
The current behavior is because that's what the lines function does elsewhere in the Haskell ecosystem, such as the bytestring package.

**Comment by kqr** [comment]
Fair enough! Doing the least surprising thing sounds like a good reason. :)
