### ISSUE TITLE
network-conduit-tls:  Handshake Failure for Self-Signed Certificate

### ISSUE THREAD

**Issue by jazzyeagle** [snoyberg/conduit#245]
Hello -

I'm trying to create a TLS server and an associated TLS client using network-conduit-tls, and everything is now compiling.  I'm running both the client and server on the same machine with a Self-Signed Certificate created on the machine.  When attempting to connect the client to the server, I get the following error:  "HandshakeFailed (Error_Protocol ("certificate rejected: [SelfSigned]",True,CertificateUnknown))"

I was thinking that there should be a way as part of the tlsClientConfig call that you can tell it to trust self-signed certificates (or even invalid ones), especially given that self-signed certificates are used a lot for development purposes, so folks don't have to go out and buy a certificate.

I'm not sure my Haskell skills are savvy enough to actually implement this for you, but I did want to at least provide the recommendation.  If you feel there should be another way to handle this, I'd love to hear your recommendations.

Thanks!!

**Comment by snoyberg** [comment]
You can modify the [TLSSettings](http://haddock.stackage.org/lts-5.1/connection-0.2.5/Network-Connection.html#t:TLSSettings) using [tlsClientTLSSettings](http://haddock.stackage.org/lts-5.1/network-conduit-tls-1.2.0.1/Data-Conduit-Network-TLS.html#v:tlsClientTLSSettings), which allows more fine-grained control of certificate checking.

**Comment by jazzyeagle** [comment]
I'm not sure I follow your recommendation.

I see within tlsClientTLSSettings settingDisableCertificateValidation, which allows me to disable the Certification Validation, which, for what I'm working on at the moment, should be alright, because the client code I'm using right now probably won't be what I use for the actual client.

I'm also seeing TLSSettings ClientParams for "the power users", but even under there, I'm not finding where it specifically allows me to simply trust self-signed certificates without disabling validation altogether.

I even thought of error handling, but I'm not sure how to tell TLS "look, you got this error, but it's ok, connect to the server anyway".

I'm just looking for a way to tell the client that it can trust self-signed certificates.  Do you have any ideas on how to do this?

**Comment by snoyberg** [comment]
Questions on how to configure the tls library itself could probably be
better answered elsewhere, I'm not familiar with the internals. This
library just provides a thin conduit wrapper on top of tls.

**Comment by snoyberg** [comment]
Closing as upstream issue.
