### ISSUE TITLE
[cereal-conduit] UpstreamTerminationHandler for conduitGet?

### ISSUE THREAD

**Issue by nikmikov** [snoyberg/conduit#246]
I am trying to parse OpenStreetMap data, which is basically a binary stream of protocol buffer messages, using combination of  cereal-conduit and protobuf packages. The current problem with using cereal-conduit is that when  the upstream terminates, the conduitGet just returns leftover which would be discarded, although it has partial result, which needs just end-of-stream signal to complete parsing. 

Here is a simplified sketch of my pipeline:
`
OSM data file => OsmBlocks => Conduit.Zlib => OSM Primitive Block => OSM Primitives 
`  
 
Would it make sense to add by analogy with sinkConduit something like:
```haskell
        type ConduitTerminationHandler m o = (BS.ByteString -> Result o) -> C.Conduit BS.ByteString m o

        terminationHandler f = case f BS.empty of
              Fail msg _ -> pipeError $ GetException msg
              Done r lo -> C.leftover lo >> C.yield r
              Partial _ -> pipeError $ GetException "Failed reading: Internal error: unexpected Partial."   
````

**Comment by snoyberg** [comment]
Why can't you simply consuming all remaining bytes after the `conduitGet` finishes running?

**Comment by nikmikov** [comment]
Not sure I understood you. If you meant consuming lefovers from conduitGet, than it would be impractical as the Get it runs is quite expensive, and I will end up running it twice for each block.

 
Let me show you some code may be I am  just approaching the problem from the wrong side.


```haskell
import Data.Serialize(Get,getWord32be)
import Data.Conduit
import qualified Data.ProtocolBuffers as PB
import qualified Data.Conduit.Combinators as CC
import qualified Data.Conduit.Zlib as CZ

-- | Binary file contains a sequence of Blobs, prefixed with 4-byte blob length
--   each Blob, contains a single field zlib_data, which contains zlib
--   compressed protobuf serialized instance of PrimitiveBlock
data Blob = Blob {
      zlib_data :: Required 1 (Value BS.ByteString)
    } deriving (Generic)

instance Decode Blob

decodeBlob :: Get Blob
decodeBlob = getWord32be >>= PB.decodeFixedLengthMessage . fromIntegral

-- | each PrimitiveBlock contains a sequence of nodes
data PrimitiveBlock = PrimitiveBlock {
      nodes :: Repeated 1 (Message Node)
      } deriving (Generic)

instance Decode PrimitiveBlock

decodePrimitiveBlock :: Get PrimitiveBlock
decodePrimitiveBlock = PB.decodeMessage

-- | And finally Node it's just a pair of latitude and longitude
data Node = Node {
      nodeLat :: Required 1 (Value Int64)
    , nodeLon :: Required 2 (Value Int64)
    } deriving (Generic, Show)     

instance Decode Node

fileToPrimitives :: FilePath -> IO ()
fileToPrimitives filePath = do
    runResourceT $
               CC.sourceFile filePath
                   $$ conduitGet getBlob
                   =$= CC.map (PB.getField . zlib_data)
                   =$= CZ.decompress CZ.defaultWindowBits
                   =$= conduitGet decodePrimitiveBlock  -- problem here
                   =$= CC.concatMap (PB.getField . nodes)
                   =$= CC.print
```
This code will output nothing as everything is lost in discarded leftovers.

currently I can get around with
replacing
```haskell
        conduitGet decodePrimitiveBlock
         =$= CC.concatMap (PB.getField . nodes)
```
with
```haskell
        sinkGet decodePrimitiveBlock
        >>= CC.yieldMany . PB.getField . nodes
```

But I do think that initial solution with conduitGet would be more elegant. Any suggestions much appreciated!

**Comment by snoyberg** [comment]
Can you demonstrate the problem in a minimal example that doesn't involve external libraries or files that I don't have access to? I don't really understand what you're asking for.

**Comment by nikmikov** [comment]
I've tried to make it simple this time

Given: [[Int64]] represented as a text stream where each line is [Int64], encoded into binary string and then into text using base64 encoding. There is no line break at the end of the stream (this is important!)

Decoding is using cereal-conduit and print sums of each decoded list into stdout.

```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Data.Int
import Data.Binary(put)
import Data.Binary.Put
import Data.Serialize(get)
import Data.Serialize.Get
import qualified Data.ByteString.Base64 as B64
import Data.ByteString.Lazy(fromStrict, toStrict)
import qualified Data.ByteString as BS
import qualified Data.Text as T
import Data.Text.Encoding(decodeUtf8, encodeUtf8)
import Control.Applicative

import Data.Conduit( ($$),(=$=) )
import qualified Data.Conduit.Binary as CB
import qualified Data.Conduit.Combinators as CC
import Data.Conduit.Cereal(conduitGet)

example :: [[Int64]]
example = [ [1..5000], [10000..150000], [300000..340000] ]

-- | serialize lists of 64-bit integers into base64 encoded strings delimited with \0 byte
--   !! there is no \0 byte after last element
encodeExample :: [[Int64]] -> BS.ByteString
encodeExample = encodeUtf8 . T.intercalate "\0"
                . map ( (decodeUtf8 . B64.encode) . toStrict . runPut . put)

-- | decode \0 terminated bytestring
decodeNul :: Get BS.ByteString
decodeNul = go []
    where go xs = do
            b <- getWord8
            if b == 0
            then return $ BS.pack $ reverse xs
            else go (b:xs)

-- | consume all remaining input and return it as a bytestring
decodeRem :: Get BS.ByteString
decodeRem = remaining >>= getBytes . fromIntegral

decodeWithCereal :: Get BS.ByteString
decodeWithCereal = decodeNul <|> decodeRem

main :: IO()
main = do
  let ex = encodeExample example
  putStrLn "Expected:"
  mapM_ (print . sum) example
  putStrLn "Actual:"
  CB.sourceLbs (fromStrict ex)
        $$ conduitGet decodeWithCereal
        =$= CC.decodeBase64
        =$= conduitGet (get::Get [Int64])
        =$= CC.mapM_ ( print . sum )
```

Here I created a small project comparing behaviour of binary-conduit and cereal-conduit on the code below. binary-conduit handles the termination correctly (or at least as I would expect it) 
https://github.com/nikmikov/conduit-cereal-vs-binary

**Comment by snoyberg** [comment]
I have a more minimal demonstration of the problem:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import           Control.Monad.Trans.Resource (runException)
import           Data.ByteString              (ByteString)
import           Data.Conduit                 (yield, ($$), (=$))
import           Data.Conduit.Cereal          (conduitGet, sinkGet)
import qualified Data.Conduit.List            as CL
import           Data.Serialize.Get           (Get, getBytes, remaining, runGet)

getter :: Get ByteString
getter = do
    x <- remaining
    if x == 0
        then fail "nothing left"
        else getBytes $ fromIntegral x

main :: IO ()
main = do
    print $ runGet getter "hello"
    print $ runException $ yield "hello" $$ sinkGet getter
    print $ runException $ yield "hello" $$ conduitGet getter =$ CL.consume
```

Looking at the test suite, it looks like the behavior being demonstrated may be inherent to the expected behavior of the API, though I agree that this is buggy. I may end up providing alternative `conduitGet` and `sinkGet` functions and deprecating the old ones to avoid accidentally breaking existing code.

**Comment by snoyberg** [comment]
Actually, some of the problem is in the original code, due to a misuse of `remaining`. See the docs:

> Get the number of remaining unparsed bytes. Useful for checking whether all input has been consumed.

> WARNING: when run with runGetPartial, remaining will only return the number of bytes that are remaining in the current input.

Therefore, usage of `remaining` in `cereal-conduit` is not reliable.

**Comment by snoyberg** [comment]
This seems to be a reliable way to get all remaining bytes:

```haskell
slurp :: Get ByteString
slurp =
    loop id
  where
    loop front = do
        x <- remaining
        if x == 0
            then do
                mbs <- optional $ lookAhead $ getBytes 1
                case mbs of
                    Nothing -> do
                        let bs = S.concat $ front []
                        if S.null bs
                            then fail "no bytes remaining"
                            else return bs
                    Just _ -> loop front
            else do
                bs <- getBytes $ fromIntegral x
                loop (front . (bs:))
```

**Comment by nikmikov** [comment]
Yes I agree, but the use of _remaining_ was intentional and as you can see it's used just if first parser fail at the end of stream:
```haskell
decodeWithCereal = decodeNul <|> decodeRem
```
the purpose was just to emulate for testing purposes functions from _binary_, missing in _cereal_:
```haskell
import Data.Binary.Get(getLazyByteStringNul, getRemainingLazyByteString )

decode = getLazyByteStringNul <|> getRemainingLazyByteString
```
In binary they handle correctly chunked input

Basically I wanted just create simple parser for demonstration that will split the stream based on separator, but does not expect that stream ends with the separator.

**Comment by snoyberg** [comment]
Using `remaining` at all in cereal-conduit will not work, and that is not a bug in cereal-conduit.

**Comment by snoyberg** [comment]
I've pushed a commit which adds `conduitGet2` (turns out `sinkGet` works correctly). Can you test it out for your use case?

**Comment by nikmikov** [comment]
I've replaced conduitGet with conduitGet2 in my original code (parsing protobuf encoded stream) and everything works now.
Thanks!

**Comment by snoyberg** [comment]
Thanks for confirming, I've just released this to Hackage.
