### ISSUE TITLE
Release a version of resourcet that permits transformers 0.5.*

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/conduit#249]
The current release on Hackage, 1.1.7.1, does not support transformers 0.5. It would be good if it did.

I'm not entirely sure how things got into this state, as the package version bump (9a4047585c9174bc1dc9ec6066ea1509060a6b29) seems to have occurred after the dependency bump (c005f5322ec5324e53b4fe9558e7670ed9e792bc), so it seems a little weird. Perhaps they got reordered in time after a merge?

You may want to eliminate the upper bounds on base packages such as transformers, as some great minds have previously argued: https://mail.haskell.org/pipermail/libraries/2014-April/022597.html - specifically I'm trying out GHC 8.0 RC2, and...

> ... beta testers of GHC will be sending reports to please support the new GHC, this just makes it
slightly easier for those beta testers to get useful reports to maintainers.

**Comment by snoyberg** [comment]
> some great minds

That's true. In addition, I said something like that too.

**Comment by ndmitchell** [comment]
Thanks!
