### ISSUE TITLE
ungzip does not work with gzip files created by concatenation

### ISSUE THREAD

**Issue by luispedro** [snoyberg/conduit#254]
The gzip format allows one to just `cat` files together. I.e.,

    cat f1.gz f2.gz > combined.gz

should be decompressed as if the combined decompressed contents of `f1.gz` and `f2.gz` were in `combined.gz`. However, the implementation in `Data.Conduit.Zlib.ungzip` does not implement this correctly.

Example code:

    import qualified Data.Conduit as C
    import qualified Data.Conduit.List as CL
    import qualified Data.Conduit.Binary as CB
    import Data.Conduit (($$), (=$=))
    import qualified Data.Conduit.Zlib as CZ
    import Control.Monad.Trans.Resource (runResourceT)

    countC = CL.fold (\n _ -> (n+1)) (0 :: Int)
    main = do
        nl <- runResourceT $
            CB.sourceFile "combined.gz"
                =$= CZ.ungzip
                =$= CB.lines
                $$ countC
        print nl

Now take a couple of compressed files and `cat` them together into `combined.gz`.
The above programme will only count lines from the first file!

**Comment by snoyberg** [comment]
FWIW, same behavior exists in the zlib package:

```haskell
import qualified Data.ByteString.Lazy as L
import Codec.Compression.GZip

main :: IO ()
main = do
    lbs <- L.readFile "helloworld.gz"
    print $ decompress lbs
```

The behavior is most likely coming from streaming-commons. Do you have any insight into what needs to be changed in the C-library calls to zlib to make this work as expected?

**Comment by snoyberg** [comment]
Actually, I think I see how to solve this easily...

**Comment by snoyberg** [comment]
The current API is correct for allowing users to easily get one entity at a time (which does happen, see https://github.com/fpco/streaming-commons/issues/20). Instead of changing the behavior of the main functions, I've added a new `multiple` combinator to make it easy to decode an entire concatenated stream. This is now on master, can you give it a shot before release?

**Comment by luispedro** [comment]
Works on my side.

It's obviously your call, but I would argue the interface should be the other way around: `ungzip` gets all the objects (so that it's like `gunzip` or `zcat` on the command line) and a special other call (`ungzip1` or something) gets a single one.

**Comment by luispedro** [comment]
Thanks for the very fast response, by the way!

**Comment by snoyberg** [comment]
No problem. I've released this to Hackage, so closing.

Regarding which default behavior is better: you're probably right, except for the issue of backwards compatibility. I'm keeping the old behavior as-is to avoid (silently) breaking people's code.

**Comment by luispedro** [comment]
Sorry, I spoke too soon. In the new version, I can trigger an error in zlib.

    echo "One line" | gzip > 1.gz
    (for _ in $(seq 1129); do cat 1.gz ; done) > combined.gz

This works.

    (for _ in $(seq 1130); do cat 1.gz ; done) > combined.gz

Now the file `combined.gz` will trigger a (-3) zlib exception. I can also do it with less contrived examples

Here is what's happening: 1.gz is 29 Bytes (on my system, you may have to adjust the math), 1130 * 29 = 32770 > 32768 =  2^{15} so there is some internal buffer that is overflowing. This is very consistent.

**Comment by luispedro** [comment]
If I understand how things are working correctly, even without the use of `multiple`, `ungzip` will consume the whole input after the first object into memory (and then re-emit it as a leftover).

**Comment by snoyberg** [comment]
This is a more fundamental bug around leftover handling actually, and not related to multiple chunks. I've pushed two new test cases that demonstrate the problem. Thanks for the report, I'll get a new version out soon with a fix.

**Comment by snoyberg** [comment]
OK, new version is now on Hackage
