### ISSUE TITLE
Would it make sense to have `idC` primitive?

### ISSUE THREAD

**Issue by mrkkrp** [snoyberg/conduit#255]
Sort of identity conduit, should be quite useful in some cases:

```haskell
idC :: Conduit a m a
idC = awaitForever yield
```

**Comment by snoyberg** [comment]
It's not actually a true left-identity due to leftovers, e.g. the following are different:

```haskell
foo = idC =$= leftover "hello"
bar = leftover "world"
```

**Comment by mrkkrp** [comment]
So, this means there cannot be identity conduit at all?

**Comment by snoyberg** [comment]
That's correct, it's one of the key points in the design space between conduit and pipes actually.

**Comment by mrkkrp** [comment]
OK, closing this then.

**Comment by mrkkrp** [comment]
Can you give an example where we would actually get different results with `foo` and `bar` (well, assuming that `"hello"` and `"world"` are the same string :-D)?

I initially did not give this much thought, but it appears that

```
leftover "world"
```

Appends `"world"` to input stream, while

```
idC =$= leftover "hello"
```

`await`s and `yield`s entire stream and then appends `"hello"` to empty
stream.

Now I'm trying to show myself difference from point of view of downstream consumer. Let's have:

```haskell
main = runConduitRes (sourceFile "foo" =$= idC =$= leftover "hello" =$= sinkFile "bar")
```

This produces empty `"bar"` file of course no matter what we have in `"foo"`, because `leftover "hello"` conduit does not ever yield so when downstream requests a value we finish right away. With this example `idC` does not make difference, we finish immediately in both cases.

Next attempt is to make `leftover` actually `await` and `yield`:

```haskell
main = runConduitRes (sourceFile "foo" =$= idC =$= foo =$= sinkFile "bar")

foo = do
  leftover "hello"
  awaitForever yield
```

The same result with and without `idC`: `"hello"` is prepended to contents of `"foo"` file. The reason is, of course, that `leftover` took its place before we read first chunk of the file because `awaitForever yield` part goes after `leftover`.

I'm not sure how to get different results with `idC =$= leftover "hello"` and `leftover "hello"`. I have to admit this is the only thing I don't understand about the library right now and I can't stop thinking about it.

Any ideas?

**Comment by snoyberg** [comment]
Try `foo >>= await` vs `bar >>= await`.

**Comment by mrkkrp** [comment]
Ah I thought there may be a difference when composing with `=$=`… Yes indeed, with monadic bind there is difference, looking at the code it's not that surprising… Thanks!
