### ISSUE TITLE
sinkGet problems, memory leak problems with leftover

### ISSUE THREAD

**Issue by ondrap** [snoyberg/conduit#259]
I'm fighting with cereal-conduit (and tried event binary-conduit with same behaviour) and I think there are some problems with the sinkGet function.
- the `runGetPartial` function uses empty string as an indiction that there is end of input. Somehow starting the parsing with `runGetPartial get ""` causes it to behave incorrectly - it refuses to decode correctly my data (mostly using the `<|>` operator, but even without it it doesn't behave well. The `sinkGet` function does that.

Also, I tried the following 2 versions of the same thing (I need to use the second version):
```
decodeFrame = conduitGet2 get =$= CL.map (\(InputData frame) -> frame)
```
and alternative:
```
decodeFrame = do
  inpframe <- sinkDecode
  case inpframe of
    Nothing -> return ()
    Just (InputData frame) -> do
        yield frame
        decodeFrame
```
The second version leaks memory as hell. I have no idea what is causing it, but unlike the first version it is using lots of `leftover`. The thing is running in `runResourceT . runConduit`. The `sinkDecode` function is my replacement of `sinkGet`; `sinkGet` somehow worked when I ran something like `await >>= leftover . fromJust` before that.

**Comment by snoyberg** [comment]
A self contained example demonstrating the memory leak will expedite this.

**Comment by ondrap** [comment]
I have created a sample, but I need a test file. I will try to make it without the testfile (must be quite a big one) and post it. However, it seems to me this will be very interesting as it appears only when I run the whole job in `forever` (I have put `threadDelay` at the and and killed it with Ctrl-C). It seems to me the culprit will be some GHC optimization.

**Comment by ondrap** [comment]
The repository that exhibits the bug is here: https://github.com/ondrap/ghc-memory-leak
It seems to be triggered by some optimization, I will update the repo if I find new information.

**Comment by ondrap** [comment]
It seems that I have come across this: https://ghc.haskell.org/trac/ghc/ticket/917 . I don't know what happens that this is triggered, but it's somewhat disconcerting when you use conduits to avoid space leaks :)

**Comment by snoyberg** [comment]
There are lots of non-idiomatic things going on in that example, such as using `openFile` to open a `Handle` and never closing it, as opposed to just using `withFile` or `sourceFile`. It's also not clear to me at this point that this is actually relevant to conduit, as the code in conduit-extra seems to not reproduce the issues at all.

**Comment by ondrap** [comment]
I have updated the repo. The `decodeFrame` function now looks like this:
```
decodeFrame :: (MonadThrow m, MonadIO m) => Conduit BS.ByteString m Frame
-- decodeFrame = conduitGet2 get
decodeFrame = do
  -- inpframe <- sinkDecode
  -- inpframe <- sinkGet get
  inpframe <- optional (sinkGet get)
  case inpframe of
    Nothing -> return ()
    Just dta -> yield dta >> decodeFrame
  where
    optional sink = do
      item <- await
      case item of
        Nothing -> return Nothing
        Just dta -> leftover dta >> Just <$> sink
```
- if you use the `conduitGet2` version, it doesn't leak
- if you use the `sinkDecode` (my version of `sinkGet`) it leaks (142MB used)
- if you use the `sinkGet get` function, it immediately fails (IMO the reason is that the `runGetPartial` is run with empty string for the first time)
- if you use `optional (sinkGet get)` it leaks a lot (421MB), and it works

I have no idea why the `sinkGet get` doesn't work as opposed to `optional (sinkGet get)`. But this behaviour appears to be a bug somewhere in conduit/conduit-extra. As for the memory leak, that might be a feature or a bug in GHC - I will try some other tests, what bothers me is that in my production code it seems that the memory is never released, although the threads that allocated it and all the data is never used or referenced later.

**Comment by ondrap** [comment]
The decoding error is mine, there are different types being decoded for sinkGet and sinkDecode. I will look into the memory leak, but that looks like some GHC-specific thing.

**Comment by snoyberg** [comment]
Closing as a non-conduit issue, if this is in error, please ping the issue.
