### ISSUE TITLE
conduit-extra-1.1.12: <$>, <*> not in scope

### ISSUE THREAD

**Issue by juhp** [snoyberg/conduit#260]
While trying to build pandoc-citeproc-0.9.1.1 on Fedora with ghc-7.8.4, for conduit-extra-1.1.12 I ran into:
https://copr-be.cloud.fedoraproject.org/results/petersen/pandoc/fedora-24-x86_64/00171743-pandoc/

```
Data/Conduit/Process.hs:106:9: Not in scope: `<$>'
Data/Conduit/Process.hs:107:9: Not in scope: `<*>'
Data/Conduit/Process.hs:108:9: Not in scope: `<*>'
```

I see it built in travis - so I am not sure what the problem is.
Maybe some library compatibility issue?
https://travis-ci.org/snoyberg/conduit/jobs/119180466
Any ideas?

**Comment by taphu** [comment]
I am also having a similar problem. Also, I'm not 100% sure I know what I'm looking at, but in the link to travis that @juhp posted, the issue seems to be present:
https://travis-ci.org/snoyberg/conduit/jobs/119180466#L317

**Comment by juhp** [comment]
Ah, doh Rick is right - I just saw that the travis job was green so I had
assumed it was okay there...

**Comment by tmcgilchrist** [comment]
I've made a first attempt at fixing this issue here https://github.com/snoyberg/conduit/pull/261

**Comment by snoyberg** [comment]
I've got the Travis build fixed now so that it fails properly. I'll look at
your PR next Tim, thanks.

**Comment by snoyberg** [comment]
I've released a new version of conduit-extra to Hackage (which also fixes a breaking change in a function signature). Let me know if the problem persists.

**Comment by juhp** [comment]
Thanks Michael - looks good to me - my pandoc build succeeded now. :)
