### ISSUE TITLE
Data.Conduit.List.consume documentation outdated, does it have a lazy version?

### ISSUE THREAD

**Issue by blueonyx** [snoyberg/conduit#266]
i would have liked a lazy Data.Conduit.List.consume and [it's haddock](http://hackage.haskell.org/package/conduit-1.2.6.6/docs/Data-Conduit-List.html#v:consume) says there is one in Data.Conduit.Lazy which doesn't exist (anymore?).

**Comment by snoyberg** [comment]
It does exist, it's just in conduit-extra:

https://s3.amazonaws.com/haddock.stackage.org/lts-6.0/conduit-extra-1.1.13.1/Data-Conduit-Lazy.html
