### ISSUE TITLE
Merge multiple sorted sources

### ISSUE THREAD

**Issue by cblp** [snoyberg/conduit#268]
I have written it, see https://github.com/cblp/conduit-merge

And I want it to be incorporated into conduit package. Is it good idea?

**Comment by snoyberg** [comment]
For now, I'd recommend keeping it in a different package, which will give you flexibility to evolve the API as necessary without being constrained by conduit's slow moving nature as a stable package.

**Comment by cblp** [comment]
Is conduit-extra a better place for it?

**Comment by snoyberg** [comment]
Probably conduit itself is the right place, it's just that I'm hesitant to add functions that have any possibility of changing their types or behaviors over time. I have a feeling that some real-world usage may demonstrate desired changes for this function.

**Comment by cblp** [comment]
Ok.
