### ISSUE TITLE
conduit-extra-1.1.13.2 test suite failure on NixOS x86_64

### ISSUE THREAD

**Issue by peti** [snoyberg/conduit#271]
Citing from http://hydra.cryp.to/build/1867668/nixlog/1/raw:

~~~
Failures:

  test/Data/Conduit/ProcessSpec.hs:81: 
  1) Data.Conduit.Process.Data.Conduit.Process blocking vs non-blocking
       uncaught exception: ErrorCall (Took too long for sleep to exit, your system is acting funny
       CallStack (from HasCallStack):
         error, called at test/Data/Conduit/ProcessSpec.hs:91:22 in main:Data.Conduit.ProcessSpec)
~~~~

**Comment by snoyberg** [comment]
Looks like the Nix machine is taking too long for sleep to exit, that error indicates a system-specific issue.

**Comment by peti** [comment]
Yeah, it appears the build machin was simply exceptionally busy when that timeout occurred. I have not been able to re-produce this issue since, so it's almost certainly a system  problem.
