### ISSUE TITLE
Version of sinkSocket that sinks builders?

### ISSUE THREAD

**Issue by DaveCTurner** [snoyberg/conduit#279]
I've recently been hunting for, but failed to find, a function with approximate type

    MonadIO m => Socket -> Consumer Data.ByteString.Builder.Builder m ()

that's a bit cleverer than just `\skt -> map (toChunks . toLazyByteString) =$= sinkSocket skt`.

My situation is that I'm streaming a bunch of data out of a database and munging it a bit, yielding a stream of `Builder`s. The issue with the function above is it ends up allocating a buffer and calling `send()` on each item, and this seems to be a limiting factor in terms of performance.

To solve this I think it would help to take control of the buffers directly and run multiple `Builder`s in each one, only calling `send()` when the current buffer is full or explicitly flushed. I _think_ this is possible using the lower-level `Data.ByteString.Builder.Extra.BufferWriter` although I've not tried yet.

So, three questions:

1. Does this function actually exist?
2. If not, is it because it's not actually implementable?
3. If not, would it be generally useful?

**Comment by snoyberg** [comment]
How about fusing with the `builderToByteString` function?

https://www.stackage.org/haddock/lts-7.0/conduit-extra-1.1.13.2/Data-Conduit-Blaze.html#v:builderToByteString

**Comment by DaveCTurner** [comment]
D'oh, completely missed that entire module! Thanks, that's exactly what I wanted.
