### ISSUE TITLE
Any love for `mapAccum_`?

### ISSUE THREAD

**Issue by erikd** [snoyberg/conduit#285]
I've now implemented the function:
```
mapAccum_ :: Monad m => (a -> s -> (s, b)) -> s -> Conduit a m b
```
a number of times in different projects and wonder if its not time to add it to `Data.Conduit.List`. This is just like `mapAccum` but the terminal value of the state variable `s` is just dropped.

Or maybe it makes more sense to add a combinator that does:
```
ConduitM a b m r -> Conduit a m b
```

**Comment by snoyberg** [comment]
I don't mind adding the suggested function, but I believe your requested
combinator already exists: void.

**Comment by erikd** [comment]
Bah, now I feel like a dunce!

Of course `void (DC.mapAccum f s)` is equivalient to what I proposed.
