### ISSUE TITLE
Feature request: generalize resourceForkIO

### ISSUE THREAD

**Issue by centromere** [snoyberg/conduit#291]
It would be very convenient to generalize the [`resourceForkIO`](https://www.stackage.org/haddock/lts-7.13/resourcet-1.1.8.1/Control-Monad-Trans-Resource.html#v:resourceForkIO) function so that I can have it use `async` instead of `forkIO`. My proposal is for a function with this type signature:

`resourceForkWith :: MonadBaseControl IO m => (IO () -> IO a) -> ResourceT m () -> ResourceT m a`

**Comment by snoyberg** [comment]
I'm OK with that, want to send a PR?
