### ISSUE TITLE
Possible addition to Data.Conduit.List (batch :: Int -> Conduit a m [a])

### ISSUE THREAD

**Issue by tomsmalley** [snoyberg/conduit#295]
There may already be a nice way to do this that I have missed, but I found myself needing to batch items up for a downstream consumer (which was writing to a database and limited by transactions / sec). For example:

```haskell
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
> runConduit $ CL.sourceList [1..17] =$ batch 5 =$ CL.iterM print =$ CL.sinkNull
[1,2,3,4,5]
[6,7,8,9,10]
[11,12,13,14,15]
[16,17]
```

Would others find this useful or is it too specialised to add?

I implemented it by a minor modification to `groupBy`

```haskell
batch :: Monad m => Int -> Conduit a m [a]
batch n =
    start
  where
    start = await >>= maybe (return ()) (loop n id)

    loop count rest x =
        await >>= maybe (yield (x : rest [])) go
      where
        go y
            | count > 1 = loop (count - 1) (rest . (y:)) x
            | otherwise = yield (x : rest []) >> loop n id y
```

**Comment by snoyberg** [comment]
Seems like a good addition to me. Looks like a name more in line with the
rest of the ecosystem may be chunksOf:

https://www.stackage.org/lts-7.19/hoogle?q=chunksOf

PR certainly welcome.

**Comment by tomsmalley** [comment]
Well spotted, I submitted a PR (#296) but it doesn't include a chunksOfS version.
