### ISSUE TITLE
Question about `groupBy` implementation

### ISSUE THREAD

**Issue by erikd** [snoyberg/conduit#300]
Hi Michael,

The `groupBy` implementation is as follows:
```
groupBy, groupByC :: Monad m => (a -> a -> Bool) -> Conduit a m [a]
groupByC f =
    start
  where
    start = await >>= maybe (return ()) (loop id)

    loop rest x =
        await >>= maybe (yield (x : rest [])) go
      where
        go y
            | f x y     = loop (rest . (y:)) x
            | otherwise = yield (x : rest []) >> loop id y
```
Why have you defined `start` like that instead of just inlining the body of `start` at the one and only position it is used?

**Comment by snoyberg** [comment]
Probably just habit of applying the worker/wrapper transform, though (as you point out) it probably isn't needed here since `loop` is already factored out, so factoring out `start` likely doesn't add anything. In other words: likely nothing deep happening here.

**Comment by erikd** [comment]
Thanks Michael. I may submit a PR to clean that up. Mainly just to make the code more readable because whenever I need to do some low level `Conduit` work, your code is the first place I look :).
