### ISSUE TITLE
passthroughSink misses last value?

### ISSUE THREAD

**Issue by AlexeyRaga** [snoyberg/conduit#304]
I have the following program:

```
printSink :: (MonadIO m, Show a) => Sink a m ()
printSink = awaitForever $ \x -> liftIO (print x)

main :: IO ()
main = do
   res <- runConduit $ inputStream .| passthroughSink (printSink) (const $ return ()) .| L.take 5
   print res
```

It looks like the last value is never passed into a sink inside `passthroughSink`:

```
("a1","a1")
("a2","a2")
("a3","a3")
("b1","b1")
[("a1","a1"),("a2","a2"),("a3","a3"),("b1","b1"),("b2","b2")]
```

First 4 lines are prints from within `printSink`, the last one is from `main` and it contains all 5 elements as expected.

Is it a bug or I am doing something wrong?

**Comment by snoyberg** [comment]
Very nice catch! The bug is pretty tricky, I've added a lengthy comment in my commit. Can you review, try out the code, and let me know if it fixes your issue?

**Comment by AlexeyRaga** [comment]
Read the comments and it looks good to me, thanks for an explanation!
It also answers another question I had in my mind: whether `yield` to downstream happens before or after the value is passed through the sink.
In some situations, it is important that the sink "sees" the value first and the downstream second, as far as I understand, it is what happens now.
Thanks again for a quick response and a fix!

**Comment by snoyberg** [comment]
Thanks for the report and the quick response, new version is on Hackage.
