### ISSUE TITLE
questions about exception handling

### ISSUE THREAD

**Issue by flip111** [snoyberg/conduit#310]
# Y #
https://hackage.haskell.org/package/conduit-1.2.10/docs/Data-Conduit.html#g:7

http://www.yesodweb.com/blog/2014/01/conduit-transformer-exception

```haskell
main :: IO ()
main = runResourceT $ src $$ sinkFile "/does/not/exist/output.txt"

src :: Source (ResourceT IO) ByteString
src = sourceFile "/does/not/exist/input.txt" `catchC` \e ->
    yield (pack $ "Could not read input file: " ++ show (e :: IOException))
```

Looking at the type signature of `src` i understand that `catchC` transforms the exception to a bytestring which is then put back into the conduit with `yield`. I don't understand this use-case, when you have a CLI app you want errors displayed on stderr and not written to the output file...

Then i thought `catchC` is the wrong function for this and i should look at `tryC` ... first i don't find any example or any usage of `tryC` after long time using google. I was not able to create working code with `tryC`.

My initial expections about `tryC` (after not inspecting the type carefully) was that it would be compatible with a handler such as this:

```haskell
inputFileExceptionHandler :: MonadIO m => Conduit (Either IOException BSC.ByteString) m BSC.ByteString
inputFileExceptionHandler = awaitForever $ \result -> case result of
  Left ex    -> liftIO $ hPutStrLn stderr $ "Input file error: " ++ ioe_description ex
  Right byte -> yield byte
```

However this is not the case, because (in counter to my expectations) the `tryC` function does not continue the stream with an `Either` instead the `Either` is moved to the result of the entire conduit. So type signature is
```haskell
tryC :: (MonadBaseControl IO m, Exception e) => ConduitM i o m r -> ConduitM i o m (Either e r)
```

and i wrote my code in a way as i was expecting it to be
```haskell
tryC :: (MonadBaseControl IO m, Exception e) => ConduitM i o m r -> ConduitM i (Either e r) m r
```

What i understand from conduit and haskell in general is in order to get that final `r` you have to use `runConduit`, but if i already do `runConduit` on the input (coming from `sourceFile`) i try to run the conduit too soon before i chain it with the other functions.

# X #

Before using conduits when using the regular bytestring functions i was doing it like this
```haskell
writeToFile :: String -> B.ByteString -> IO ()
writeToFile filepath str = do
  hasWritten <- (try $ B.writeFile filepath str) :: IO (Either IOException ())
  case hasWritten of
    Left ex -> hPutStrLn stderr $ "Output file error: " <> ioe_description ex
    Right str -> return ()
```

How can i get a similar functionality with conduit? I like to make a separate error message for each thing which could go wrong, and when it does go wrong it the program should not continue with the rest of the conduit.

**Comment by snoyberg** [comment]
Can you try restating this question as what you're actually trying to
accomplish? I'm afraid that we're venturing into XY problem territory here.

**Comment by flip111** [comment]
I edited my original post to clarify what is X and what is Y. Do you need any more information about either X or Y ?

**Comment by snoyberg** [comment]
What about creating a helper data type that tags your exception with the extra info you need and rethrows from inside `catchC`? Then you can catch from outside and display whatever message you want.

**Comment by flip111** [comment]
I'm too inexperienced to know if that's a good idea, but i will try it. Was was also talking about `tryC` because i was curious to know more about it and how it works. Maybe it's not important for my problem but it would still be good to have a bit more information about it in the documentation.

**Comment by snoyberg** [comment]
It's the same as try from the base package.

**Comment by flip111** [comment]
Does that mean that the functionality of `tryC` is the same as if you would do `runConduit` first and then `try` ?

**Comment by snoyberg** [comment]
No, it means that `catch` is to `catchC` as `try` is to `tryC`. You can implement it with ``tryC m = (Right <$> m) `catchC` return . Left``.
