### ISSUE TITLE
Integration with the foldl library

### ISSUE THREAD

**Issue by cocreature** [snoyberg/conduit#311]
This is only a question not an actual issue:

At some point `conduit-extra` contained the necessary boilerplate to integrate with the `foldl` library (which I personally find quite pleasant to use). However, that code was removed in https://github.com/snoyberg/conduit/commit/147475db76b7a70209b0f6acaa056e82cbed6b64#diff-ba10cb6fed8c36fb57edf7306612a142 without any explanation. Is there a better way to achieve this these days or does the functionality still exist in some other form? If not, are you open to adding it again (probably in the form used by e.g. pipes that does not incur a dependency on the `foldl` package).

**Comment by snoyberg** [comment]
I have no objection to adding it back in, I _think_ it was an incidental removal instead of intentional. PR would be welcome 👍
