### ISSUE TITLE
Is `takeCE` gone?

### ISSUE THREAD

**Issue by SwiftsNamesake** [snoyberg/conduit#320]
The docs mention it, but I can't seem to find it in this repo.

**Comment by snoyberg** [comment]
It's in the conduit-combinators package: https://www.stackage.org/haddock/nightly-2017-08-20/conduit-combinators-1.1.1/Conduit.html#v:takeCE

**Comment by SwiftsNamesake** [comment]
Thanks for responding so quickly. I'll close.
