### ISSUE TITLE
Data.Conduit.List.iterate appears not to cache earlier computations

### ISSUE THREAD

**Issue by lobachevzky** [snoyberg/conduit#325]
I am working on a pathtracer that generates traces and hands them off to Yesod to be rendered using the Yesod.WebSockets library. My `Source` is generated using `Data.Conduit.List.iterate`. However, I noticed that the time between each iteration increases by a roughly constant amount, suggesting that earlier computations are not cached and used for subsequent computations. In other words, I would hope that `f (f x)` would use a cached version of `f x` instead of recomputing it from scratch. Is there a way to get `iterate` to do this? Thanks.

**Comment by snoyberg** [comment]
Can you include an example demonstrating the problem? I see that the `iterate` function is lazy, which _may_ be the issue, but it is certainly reusing the previously generated values.

**Comment by lobachevzky** [comment]
Sure. Sorry for the vagueness. The function that uses `Data.Conduit.List.iterate` is

```haskell
traceSource
  :: Monad m
  => Source m (Array U DIM3 Double)
traceSource =
  (Data.Conduit.List.iterate traceCanvas startValues) =$=
  (Data.Conduit.List.mapM computeArray3)
  where
    startValues = R.zipWith (,) blackCanvas startingGens
    computeArray3 = R.computeP . fromTripleArray . (R.map fst)
```

This gets fed into the web socket as follows:

```haskell
getHomeR :: Handler Html
getHomeR = do
  WS.webSockets $
    sources $$ Data.Conduit.List.map formatAsImgSrc =$= WS.sinkWSText
  defaultLayout $ do
    toWidget $(hamletFile "templates/home.hamlet")
    toWidget $(juliusFile "templates/home.julius")
  where
    sources = zipSources WS.sourceWS traceSource
```

I timed between iterations and found that the time increased somewhat evenly with each iteration:
1: 8.609 seconds
2: 15.217 seconds
3: 23.984 seconds
4: 41.159 seconds
5: 45.698 seconds
etc.

**Comment by snoyberg** [comment]
Are you able to reproduce this behavior in a standalone example?

**Comment by lobachevzky** [comment]
Let me work on that and get back to you.

**Comment by lobachevzky** [comment]
Hi Michael. It took a little while for me to nail this one down. I did my best to put together a really minimal example for you in [this gist](https://gist.github.com/lobachevzky/8e7c4762c7d192224b15a185f2be29b7). Essentially the code uses [Repa]( https://hackage.haskell.org/package/repa) to iteratively generate a large random array, add it to the previous array, and reduce it with sumP. 

I plotted the times of each iteration and this is how the graph looked: 
![seconds-per-iteration](https://user-images.githubusercontent.com/10344742/30527077-74ffa2f8-9bf2-11e7-9603-bb7b4d64bc1b.png)
 
For a simple computation like this, the times increase much more slowly than they do for my main project, where this issue is actually interfering with functionality.

**Comment by snoyberg** [comment]
I reduced this to something more minimal, using just conduit and not Yesod:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-8.12 script --optimize
{-# OPTIONS_GHC -Wall -Werror #-}

module Main (main) where

import Prelude hiding (sum)
import qualified Data.Array.Repa as R
import Data.Array.Repa (Array, DIM1, (+^), D, Z(..), (:.)(..), (!))
import Data.Conduit (($$), (=$=), Source)
import qualified Data.Conduit.List
import qualified System.Random as Random
import Data.Time

n :: Int
n = round (1e6 :: Double)

addLargeRandomArrays :: Array D DIM1 Int -> Array D DIM1 Int
addLargeRandomArrays array = array +^ array'
  where
    i = array ! (Z :. 0) -- use the first element in the array as the random seed
    array' =
      R.fromListUnboxed (Z :. n) . take n $ Random.randoms (Random.mkStdGen i) -- random array

source
  :: Monad m
  => Source m Int
source =
  Data.Conduit.List.iterate addLargeRandomArrays zeros =$= -- repeatedly add large random arrays
  Data.Conduit.List.mapM sum -- reduce each new array to its sum
  where
    zeros = R.fromFunction (Z :. n) $ const 0 -- all zeros
    sum array = (! Z) <$> R.sumP array -- reduction

main :: IO ()
main = do
  start <- getCurrentTime
  _ <- source $$ Data.Conduit.List.foldM go start
  return ()
  where
    go prev x = do
      now <- getCurrentTime
      print (diffUTCTime now prev, x)
      return now
```

Then I removed conduit as well and the problem persisted:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-8.12 script --optimize
{-# OPTIONS_GHC -Wall -Werror #-}

module Main (main) where

import Prelude hiding (sum)
import qualified Data.Array.Repa as R
import Data.Array.Repa (Array, DIM1, (+^), D, Z(..), (:.)(..), (!))
import qualified System.Random as Random
import Data.Time

n :: Int
n = round (1e6 :: Double)

addLargeRandomArrays :: Array D DIM1 Int -> Array D DIM1 Int
addLargeRandomArrays array = array +^ array'
  where
    i = array ! (Z :. 0) -- use the first element in the array as the random seed
    array' =
      R.fromListUnboxed (Z :. n) . take n $ Random.randoms (Random.mkStdGen i) -- random array

main :: IO ()
main = do
  start <- getCurrentTime
  loop start zeros
  where
    zeros = R.fromFunction (Z :. n) $ const 0 -- all zeros
    loop prev array = do
      let array' = addLargeRandomArrays array
      sum <- (! Z) <$> R.sumP array'
      now <- getCurrentTime
      print (diffUTCTime now prev, sum)
      loop now array'
```

This looks like a problem in the repa-using code, though to be honest I'm not that familiar with repa.

**Comment by lobachevzky** [comment]
Great! This is good info. I will take it up with the Repa folks.
