### ISSUE TITLE
Non-constant memory use in case of recursive transformation

### ISSUE THREAD

**Issue by reactormonk** [snoyberg/conduit#326]
I've found a case where conduit doesn't guarantee constant memory usage, see example: https://github.com/reactormonk/non-constant-memory

Replacing https://github.com/reactormonk/non-constant-memory/blob/master/src/Lib.hs#L29 with an `ana` doesn't help, but removing the recursion does.

**Comment by snoyberg** [comment]
Replacing: `foldC` with `foldlC (\x y -> force $ mappend x y) mempty` and adding appropriate `NFData` instances seems to fix it. Adding `force` calls inside `valueToTypes` seems to solve it as well. I would recommend using a strict vector type if such a thing existed. I'd _definitely_ recommend adding strictness annotations to at least the `d` field.
