### ISSUE TITLE
Space leak with conduitParser

### ISSUE THREAD

**Issue by beojan** [snoyberg/conduit#330]
I'm parsing a (multi-gigabyte) file that consists of multiline records. The conduit portion is:
```haskell
summary <- runConduitRes
     $ sourceFileBS inputFile
    .| conduitParser eventParser
    .| takeC 300000
    .| foldlC summarize (Summary 0 0 0 [] 0)
```

Memory usage grows linearly, and the heap profile ([attached](https://github.com/snoyberg/conduit/files/1385491/HepMCParser.pdf)) shows this is due to `ARR_WORDS`. The heap profile was taken by manually stopping execution, so nothing after this point has run. The list in the summary just contains a few (no more than 30) `Int`s.

It appears Bytestring input that has been successfully parsed isn't released (even though we wouldn't need to backtrack into it), so memory use is linear.

**Comment by snoyberg** [comment]
This could indicate problems in the definition of `eventParser`. The best way to get this diagnosed is to put together a minimal reproducing test case that demonstrates the problem.

Just a guess out of nowhere: do you perhaps need strictness annotations on the fields of `Summary`?

**Comment by beojan** [comment]
Summary contains a few `Double`s and a list of `Int`. If the issue were strictness annotations, wouldn't I see memory being used by `Thunk`s rather than `ARR_WORDS`?

The definition of `eventParser` is below, but I don't see anything in it that could cause an issue:
```haskell
notEOL :: Char -> Bool
notEOL c = (c /= '\n') && (c /= '\r')

nextLine :: Parser ()
nextLine = skipWhile notEOL *> endOfLine

headerLine :: Parser ()
headerLine = "HepMC" *> nextLine

int :: Parser Int
int = signed decimal

eventParser :: Parser Event
eventParser = do
  skipMany endOfLine <?> "Skip blank lines"
  skipMany headerLine <?> "Skip headers"
  (weight, numTrials) <- "E " *> (do
                                    ((count 2 (int *> space) <?> "event number and number of interactions") *>
                                     (count 3 (double *> space) <?> "event scale, alpha QCD, alpha QED") *>
                                     (count 5 (int *> space) <?> "signal ID, barcode, num vertices, two barcodes"))
                                    stateListEntries <- (int <* space) <?> "entries in state list"
                                    count stateListEntries (int *> space) <?> "state list"
                                    weightListEntries <- (int <* space) <?> "entries in weight list"
                                    guard (weightListEntries >= 5) <?> "must be >= 5 weights"
                                    weight <- (double <* space) <?> "first weight"
                                    count 2 (double *> space) <?> "discard 2 weights"
                                    numTrials <- (double <* space) <?> "num trials"
                                    (count (weightListEntries - 5) (double *> space) *> double *> endOfLine) <?> "finish E line"
                                    return (weight, numTrials)) <?> "Parse E line"
  skipMany nuhf <?> "Skip NUHF before C"
  gen_xsec <- "C " *> (do
                         xsec <- (double <* space) <?> "gen xsec"
                         (double *> endOfLine) <?> "finish C line"
                         return xsec) <?> "Parse C line"
  skipMany nuhf <?> "Skip NUHF after C"
  skipMany vp <?> "Skip VP"
  skipMany headerLine <?> "Skip trailing headers"
  return $ Event weight numTrials gen_xsec

  where
    nuhf :: Parser ()
    nuhf = ("N " <|> "U " <|> "H " <|> "F ") *> nextLine
    vp :: Parser ()
    vp = ("V " <|> "P ") *> nextLine
```

**Comment by beojan** [comment]
Actually, it turns out adding making the fields in `Summary` strict did fix the issue.
Should I close this issue, or do you think there's something warranting investigation (`foldlC` is documented as a *strict* left fold)?

**Comment by snoyberg** [comment]
This is the difference between weak head normal form (WHNF), which evaluates one level of your data, and normal form (NF), which fully evaluates your data. A similar question came up recently with #326. I wrote a relatively comprehensive blog post on the topic: https://www.fpcomplete.com/blog/2017/09/all-about-strictness.
