### ISSUE TITLE
Need to bump `conduit` dependency

### ISSUE THREAD

**Issue by nomeata** [snoyberg/conduit#340]
Hi,

it seems that this commit started to use `.|`which requires a newer version of `conduit` than specified in the `.cabal` file:

https://github.com/snoyberg/conduit/commit/efb8d0999a8f821c060d8464111c6aeb9056adb8

One way to fix this is probably to use `=$=` instead of `.|`.

**Comment by snoyberg** [comment]
In the future, clarifying which package within this repo you're referring
to would be helpful, or even just sending a PR.

**Comment by nomeata** [comment]
Sorry, I was blindly follow the “bug tracker” link from hackage. Will be more careful next time :-)

**Comment by snoyberg** [comment]
No worries, the link to the commit definitely helped.

On Wed, Dec 27, 2017 at 11:41 AM, Joachim Breitner <notifications@github.com
