### ISSUE TITLE
runResourceT doens't rethrow exceptions in finalizers

### ISSUE THREAD

**Issue by nh2** [snoyberg/conduit#346]
```
runResourceT $ allocate (return 'x') (\_x -> putStrLn "finalizer running" >> error "erroring")
```

prints only

```
finalizer running
```

and swallows the `error`.

It would be nice to have a variant of `runResourceT` that rethrows errors happening in finalizers.

**Comment by snoyberg** [comment]
Fixed in resourcet 1.2.
