### ISSUE TITLE
Broken with GHC 7.10

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/conduit#353]
It's suddenly started failing with:

```
Data/Conduit.hs:106:1:
    Control.Monad.Trans.Resource: Can't be safely imported!
```

as per https://travis-ci.org/ndmitchell/hoogle/jobs/345920878. Was this a deliberate decision to remove GHC 7.10 support?

**Comment by RyanGlScott** [comment]
FWIW, I am experiencing this issue as well (see [this Travis build](https://travis-ci.org/bos/criterion/jobs/346399563#L727)). This is with `conduit-1.2.13`, an old version, though... perhaps we just need to limit which versions of `resourcet` it can be used with, as that's where the error arises.

**Comment by RyanGlScott** [comment]
It appears that building `conduit-1.2.13` with `resourcet-1.1.3.3` (which is what both of our CI jobs picked) causes the error. If I force it to build with a more recent entry in the `resourcet-1.1.*` series, such as `resourcet-1.1.11`, then the issue goes away.

I'm not sure when exactly this was fixed, but perhaps adding a stricter lower version bound would do the trick.

**Comment by snoyberg** [comment]
I'm not sure why the dependency solver is choosing old versions. If you wish, you can add lower bounds on your resourcet and/or conduit versions in your own packages. If someone else wants to play around with adding stricter lower bounds on old versions, feel free, but I don't intend to spend time on it myself.

**Comment by ndmitchell** [comment]
Is this one for Hackage trustees (ping @hvr)? Why doesn't this show up at https://matrix.hackage.haskell.org/package/conduit? Having to manually add incorrect bounds to all my programs because of a dependent library that has incorrect bounds sounds depressing, tedious, and ultimately ineffective.

Note that while I'm not keen on adding bounds to lots of old versions, just the one version where you dropped GHC 7.10 support will get a lot of relatively recent configurations building that currently are bust. I suspect we might be the canary in the coal mine, with lots of additional packages showing up pretty soon.

**Comment by ndmitchell** [comment]
The Matrix at https://matrix.hackage.haskell.org/package/conduit is now looking pretty dire for GHC 7.10 and below.

**Comment by snoyberg** [comment]
I won't make any technical arguments around the usefulness of the build matrix here. Suffice it to say that I'm personally not particularly bothered by the idea that the dep solver is choosing silly build plans.

To work around the issue, I've released a patch release conduit-1.2.13.1, which removes the Safe Haskell pragmas. That should address the problem somewhat. However, your comment:

> Note that while I'm not keen on adding bounds to lots of old versions, just the one version where you dropped GHC 7.10 support will get a lot of relatively recent configurations building that currently are bust.

Unfortunately this likely isn't true. I don't know what's encouraging the dep solver to make the decision to choose a much older version of resourcet, but adding a lower bound in conduit is likely to only encourage it to choose an older version of conduit, not a newer version of resourcet.

**Comment by ndmitchell** [comment]
Thanks, everything all works now! The matrix also makes it quite clear what does and doesn't work, so a useful sanity check.

Agreed, the solver seems to try and make decisions in "version space" (which are very difficult) instead of "time space" (which packages were released most recently). It seems one is fraught with difficulties...

**Comment by snoyberg** [comment]
Cool, glad it's working. 😅
