### ISSUE TITLE
Docs: confusion about (.|), fuse, (=$=) and depreciation

### ISSUE THREAD

**Issue by limick** [snoyberg/conduit#356]
The documentation for `(.|)` seems to suggest that it is the same as `fuse`. However, the documentation for `fuse` says that it is a synonym for `(=$=)`. As a first time user I conclude that `(.|) = (=$=)`, and looking at the source code they indeed seem to be equivalent. However, this is not obvious just from the documentation.

**Suggestion 1**: If these functions are the same, their documentation should say so unambiguously. Currently, the function comments for `(.|)` and `(=$=)` have slightly different wordings which could suggest that they are not.

The source for `(=$=)` says `{-# DEPRECATED (=$=) "Use .|" #-}`, suggesting that `(.|)` is preferred.

**Suggestion 2**: The stackage haddocks should include the remark that (=$=) is deprecated.

This applies to [conduit-1.2.13.1](https://www.stackage.org/haddock/lts-10.8/conduit-1.2.13.1/Data-Conduit.html#v:-61--36--61-) (in LTS-10.8).

**Comment by snoyberg** [comment]
I'm definitely in favor of clarifying the docs. Would you be able to send a PR to clean this up? Note that master is on conduit 1.3, and may be significantly different from 1.2.

**Comment by limick** [comment]
Yes, I'll send a PR. I haven't spotted any relevant differences between 1.3 and 1.2 concerning this issue.
Regarding the depreciation remark: Apparently it was not included in the docs because of a dangling where clause in the definition of (=$=). I'll fix that too.
