### ISSUE TITLE
Question: What difference `sourceFile` and `sourceFileBS`?

### ISSUE THREAD

**Issue by waddlaw** [snoyberg/conduit#359]
[haddock](https://www.stackage.org/haddock/lts-11.0/conduit-1.3.0/Data-Conduit-Combinators.html#v:sourceFile) says:

```hs
-- | Stream the contents of a file as binary data.
sourceFile   :: MonadResource m => FilePath -> ConduitT i ByteString m ()
```

```hs
-- | sourceFile specialized to ByteString to help with type inference.
sourceFileBS :: MonadResource m => FilePath -> ConduitT i ByteString m ()
sourceFileBS = sourceFile
{-# INLINE sourceFileBS #-}
```

Both look the same for me.
Could you teach me what this difference?

**Comment by snoyberg** [comment]
They're the same in this version. sourceFile used to be generalized using a
type class called IOData, but that's been removed, so the comment is out of
date. Would you be interested in sending a PR to fix the comment?

**Comment by waddlaw** [comment]
Thanks @snoyberg. I understand.
OK. I'll sending PR.
