### ISSUE TITLE
Remove addCleanup / yieldOr from readme

### ISSUE THREAD

**Issue by jhrcek** [snoyberg/conduit#364]
@snoyberg thank you for this beautiful library and wonderful tutorial with exercises in README. I just found one leftover from previous versions in README, which should probably be removed. "If you want to learn more about these lower level functions, please see the API docs for addCleanup and yieldOr."

I would have created PR deleting it, but there are few sentences above it which probably won't make much sense with it being removed.. not sure..

**Comment by snoyberg** [comment]
Good catch, thanks! I've removed the entire paragraph.
