### ISSUE TITLE
`allocate_`

### ISSUE THREAD

**Issue by anacrolix** [snoyberg/conduit#367]
I frequently find myself using resourcet's allocate, with the release argument `\_ -> ...`, that is, my finalizer doesn't depend on any value. I use allocate because of its handling of asynchronous exceptions, and I think that still has value. Perhaps a function `allocate_ :: MonadResource m => IO a -> IO () -> m (ReleaseKey, a)` or `allocate_ :: MonadResource m => IO () -> IO () -> m ReleaseKey` would have some value? Have I missed some other way to do it?

**Comment by snoyberg** [comment]
I can't say I've ever needed this, but I'm open to the addition. Can you share a use case so we can figure out what the best type signature would be?

**Comment by anacrolix** [comment]
Use with [Control.Concurrent.Lock.{acquire,release}]( https://github.com/anacrolix/transcoder/blob/8873d100a6f53444fa199e5daaf671fe9088e131/Main.hs#L264) and [a custom function returning IO ()]( https://github.com/anacrolix/transcoder/blob/8873d100a6f53444fa199e5daaf671fe9088e131/Main.hs#L294).

**Comment by snoyberg** [comment]
Thanks. It seems like the first signature you mention (which returns the tuple) would be a good call here. Want to send a PR?

**Comment by anacrolix** [comment]
Cheers
