### ISSUE TITLE
Mark ResourceT as Trustworthy?

### ISSUE THREAD

**Issue by nicuveo** [snoyberg/conduit#371]
ResourceT is currently unsupported by Control.Monad.Base, but due to resourceT not being compiled as safe (or at least trustworthy), it is currently not possible to fix Control.Monad.Base.

**Comment by nicuveo** [comment]
Sorry, I should have been more clear! Truth be told, I'm new to Safe Haskell.

Basically, I want to add support for ResourceT in Control.Monad.Base, which should be a one-liner, except for the fact that Control.Monad.Base is built with -XSafe: it only agrees to import modules that are considered Safe, or at least Trustworthy. And sadly, ResourceT is neither.

If my understanding of both this Safe model and of ResourceT is correct, it shouldn't be hard for ResourceT to be dimmed trustworthy. This shouldn't have an impact, since trustworthy modules are not limited in what they can import (again, assuming my understanding is correct).

I forked the repo, I'll have a quick look to see if it's doable!

**Comment by nicuveo** [comment]
I had a look: most of resourcet can actually be marked as Safe. The only module that can only be Trustworthy is Control.Monad.Resource.Internal, due to Control.Monad.Primitive itself not being safe.

If you don't want to take the risk of making all those modules safe (which, indeed, might break if dependencies stop being safe or trustworthy), I can do instead a patch that marks them trustworthy. The only downside is that it'll add a few warnings about how the module is marked as trustworthy but is actually safe.

**Comment by nicuveo** [comment]
Yeah... in parallel I'm going to try to convince the maintainer of transformers-base to remove -XSafe, or at least perhaps to put it behind a flag. In the meantime I'll prepare the pull request that makes resourcet trustworthy, not safe, which AFAIU should be harmless (famous last words).

**Comment by nicuveo** [comment]
I am an idiot, and didn't think of the [obvious solution](https://github.com/snoyberg/conduit/pull/381).

**Comment by snoyberg** [comment]
Not going to be doing this, closing.
