### ISSUE TITLE
Document why Conduit isn't a category

### ISSUE THREAD

**Issue by bitemyapp** [snoyberg/conduit#374]
Mention why `.|` isn't `>>>` on `.|`'s documentation and perhaps link to https://stackoverflow.com/a/15263700 for explanation.

**Comment by snoyberg** [comment]
Comment added in a2125f6, what do you think?

**Comment by snoyberg** [comment]
Comment added in bb8d33a, what do you think?

**Comment by bitemyapp** [comment]
This is great, thank you!
