### ISSUE TITLE
Can ResourceT remove deriving Typeable?

### ISSUE THREAD

**Issue by iporsut** [snoyberg/conduit#377]
I'v learned about Typeable and reviewing code in `resourcet` package and found deriving `Typeable'.
I try to remove it and still run `stack test`. I have a question. Can I remove that code `deriving Typeable` from ResourceT package?

**Comment by snoyberg** [comment]
What would be the purpose of removing it? Older versions of GHC do not have automatic Typeable deriving, so I believe this would be a breaking change removing useful functionality.
