### ISSUE TITLE
Idiomatic way of composing conduits that return something other than ()?

### ISSUE THREAD

**Issue by mbwgh** [snoyberg/conduit#384]
The type signature of

```haskell
(.|) :: Monad m => ConduitT a b m () -> ConduitT b c m r -> ConduitT a c m r
```

means that every time you want to compose a conduit that returns something other like `()`, the return type is "in the way". This might be the result of a fold for instance, which usually has some summary character and then it may not be so bad.

But consider a conduit that `yield`s the current directory's immediate child directories (i.e. a shallow traversal), and `return`s the number of regular files. I want to keep up streaming by calling it recursively, and still make use of the result value. You can easily make it fit into `(.|)` of course:
```haskell
subdir :: MonadResource m => ConduitT i FilePath m Int

useSubdir = do
  ...
  nRef <- newIORef 0
  (subDir >>= writeIORef nRef) .| and .| now .| it .| fits
  ...
```

Or work in some `MonadState` or whatever. But the documentation of `(.|)` reads like the `()` in the first argument is not only a necessity, but actually desirable ("*The result value from upstream and downstream are allowed to differ between upstream and downstream.*"). Is this the case and there is actually some other clever combinator that allows me to deal with these cases more elegantly?

Don't get me wrong, the situation isn't terrible, but in my example the logic is kind of backwards in that I have to supply a continuation `(>>= k)` that is executed way later than it appears in the code.

Unfortunately, I couldn't find any mention of this in the tutorial, but that may have been just me using the wrong words to search for.

**Comment by snoyberg** [comment]
I'm not able to look into the details right now, but is `fuseUpstream` what
you're looking for?

**Comment by mbwgh** [comment]
This looks good. I was able to refactor

```haskell
subdir dir = do
  nRef <- newIORef (0 :: Int)
  sourceDirectory dir
    .| filterC nonHidden
    .| awaitForever (\fp -> do
                        isDir <- doesDirectoryExist fp
                        if isDir then yield fp else modifyIORef' nRef succ
                    )
  readIORef nRef
```

into

```haskell
subdir dir =
     sourceDirectory dir
  .| filterC nonHidden
  .| CL.mapAccumM (\fp n -> do
                      isDir <- doesDirectoryExist fp
                      pure (if isDir then n else succ n, fp)
                  )
                  0
  `fuseUpstream` filterMC doesDirectoryExist
```

I am not sure `Data.List.mapAccumM` is what I want, but that is another story.

Do you believe the `fuse*` family of functions should be mentioned in either the tutorial or in the haddocks of `(.|)`? I missed the fuse functions because they come after a large `Deprecated` section, which together with the current documentation for `(.|)` leaves you the impression that `(.|)` is and should be all there is. To be frank, I think a short mention of the limitations and work-arounds in the style of "*for ... see also ...*" would be more useful than an explanation of why conduits do not form a category.

**Comment by mbwgh** [comment]
Closing, the issue has been solved after all.
