### ISSUE TITLE
zipWithC?

### ISSUE THREAD

**Issue by rihardsk** [snoyberg/conduit#387]
Why isn't there a function
```haskell
zipWithC :: Monad m => (a -> b -> c) -> ZipConduit i a m () -> ZipConduit i b m r -> ZipConduit i c m r
```
(or something in that spirit) available in conduit? I need to do some different transformations on stream elements in parallel and then merge them back together. It seems that that a `ZipConduit` should be able to take care of the _"in parallel"_ part but how do I combine the resulting stream elements?

**Comment by snoyberg** [comment]
Short answer: it would involve an operation of unbounded memory, which we avoid. `ZipSource` is the best way to achieve what you're looking for, though it obviously has limitations.

Longer answer: it's entirely possible for a single input `i` to the two different `ZipConduit`s you provide to `zipWithC` to produce significantly different numbers of output values. Imagine a situation where the first `i` value produces 10000 values from the first `ZipConduit`, and 5 from the second. We can efficiently, in bounded memory, apply `f` to the first 5 values from both. What do we do with the other 9995 values from the first `ZipConduit`? Options may include:

* Drop them on the floor, which seems surprising
* Combine them arbitrarily with the last value from the second `ZipConduit`, which is _also_ surprising, and wouldn't work with the case where the second one produces no output
* Hold onto all of them until we get more output from the second `ZipConduit`, which is where the unbounded memory usage comes from

**Comment by rihardsk** [comment]
@snoyberg, thank you for the explanation, makes sense.

This wouldn't cause problems in my use-case though. I just want push a stream of values from a monadic source through a set of pure transformers which produce an output value for each input value as soon as it arrives. So in my case the zip could "synchronize" both of the conduits on each input/output. But i guess conduits support a more general case and so this would be tricky to achieve(?). `ZipSource` would work i guess but it seems that then i wouldn't be able to compose and reuse a bunch of "transformers" in different ways as i described previously.

I guess, what i want essentially is a sort of a conduit that's an Arrow instance. It's totally fine for me that (as i've read elsewhere) `first` would make it behave "synchronously". Do you maybe know of some other conduit-like library that would provide that?

**Comment by snoyberg** [comment]
For the situation you're describing, it sounds like you've got the following:

```haskell
pureF :: a -> b
pureG :: a -> c

f :: Monad m => ConduitT a b m ()
f = mapC pureF

g :: Monad m => ConduitT a c m ()
g = mapC pureG

combine :: b -> c -> d
```

And you want to create:

```haskell
x :: ConduitT a d m ()
```

What about:

```haskell
x = mapC (\a -> combine (pureF a) (pureG a))
```

Doing things at the pure layer allows you to see at the type level the invariant that one input results in one output. Jumping up to the conduit layer hides that invariant.

**Comment by rihardsk** [comment]
This solves a part of the problem. But i fear this approach might not be general enough. How about things involving, say, `scanlC`? What if we had
```haskell
pureG' :: c -> a -> c
cInit  :: c
g' :: Monad m => ConduitT a c m ()
g' = scanlC pureG' cInit
```
How would i then create `x :: ConduitT a d m ()`?

**Comment by snoyberg** [comment]
You're right, it wouldn't work for that case, you'd have to manually roll the two concepts together yourself.

**Comment by pbrisbin** [comment]
Hey there- I came across this Issue because I actually had a need for a different `zipWithC` in my own code base:

```hs
-- | Use a function to pair each input element with the next from of a list
--
-- >>> runConduit $ yieldMany [1..6] .| zipWithC (,) [2..] .| sinkList
-- [(1,2),(2,3),(3,4),(4,5),(5,6),(6,7)]
--
zipWithC :: Monad m => (a -> b -> c) -> [b] -> ConduitT a c m ()
zipWithC f = loop
 where
  loop [] = pure ()
  loop (x : xs) = do
    mVal <- await
    case mVal of
      Nothing -> pure ()
      Just val -> yield (f val x) >> loop xs
```

To me, this naming feels right as a conduit version of the usual `zipWith`. But I can see how it could be confusing to have a "zip" function in the library that's un-related to the `ZipSource` stuff this Issue is referring to. So my questions are:

- Am I missing a different, existing function that would do what I need here?
- If not, and if I were to create a PR, would my `zipWithC` be accepted even though it's unrelated to `ZipSource` et al?

**Comment by snoyberg** [comment]
I'm unaware of such a function, and don't see a problem with adding it. My only concern is the one you're referencing: what's a good name for it? We do need to make sure it's distinct enough versus the current usages of zip in the library.

**Comment by snoyberg** [comment]
Ah, good call on `mergeSource`, that seems to be exactly what we want here.

**Comment by rihardsk** [comment]
I got to know everything i wanted so I'll be closing this, thanks. It there's a need for a place for further discussion I can reopen the issue.
