### ISSUE TITLE
Can we generalize the Data.Conduit.Lift functions?

### ISSUE THREAD

**Issue by mbwgh** [snoyberg/conduit#389]
The Data.Conduit.Lift module provides helper functions for working with monad transformers.
Currently, this seems to go something like this:

```haskell
conduit1 :: ConduitT A B IO ()
conduit2 :: ConduitT B C (ReaderT R IO) ()

composed :: ConduitT A C (ReaderT R IO) ()
composed = (readerC . const) conduit1 .| conduit2
```

This starts to become unsatisfying when you define a typeclass involving `ConduitT` in the
type signature of it's methods. A contrived example:

```haskell
class Monad m => MonadFileSystem m where
  sourceFile :: FilePath -> ConduitT i ByteString m ()
  sinkFile :: FilePath -> ConduitT ByteString o m ()
```

If such a thing were to be even remotely useful, it should come with the corresponding mtl-boilerplate.

```haskell
instance MonadFileSystem m => MonadFileSystem (ReaderT r m) where
  sourceFile fp = readerC $ \_ -> sourceFile fp
  sinkFile fp = readerC $ \_ -> sinkFile fp
instance MonadFileSystem m => MonadFileSystem (ExceptT e m) where
  sourceFile fp = exceptC $ fmap pure $ sourceFile fp
  sinkFile fp = exceptC $ fmap pure $ sinkFile fp
```

Let's nope right outta there. If the `MonadFileSystem` class were instead defined as

```haskell
class Monad m => MonadFileSystem m where
  readFile :: FilePath -> m ByteString
  writeFile :: FilePath -> ByteString -> m ()
```

then it would be "well-behaved" in the sense that the `m` only shows up in covariant position and writing instances would be as simple as using `lift`.

If we were to define a similar typeclass like `MonadTrans`, things would be way easier:

```haskell
class MonadCTrans t where
  clift :: Monad m => ConduitT i o m a -> ConduitT i o (t m) a

-- Compare to:
class MonadTrans t where
  lift :: Monad m => m a -> t m a

instance MonadCTrans IdentityT where
  clift = identityC

instance MonadCTrans MaybeT where
  clift = maybeC . fmap pure

instance MonadCTrans (ReaderT r) where
  clift = readerC . const

instance MonadCTrans (ExceptT e) where
  clift = exceptC . fmap pure

instance Monoid w => MonadCTrans (WriterT w) where
  clift = writerC . fmap (, mempty)

instance MonadCTrans (StateT s) where
  clift x = stateC $ \s -> (, s) <$> x

instance MonadCTrans ResourceT where
  clift = resourceC . const

-- And so on...

-- This function could be considered "missing".
identityC ::
  Monad m => ConduitT i o m r -> ConduitT i o (IdentityT m) r
identityC = transPipe lift

-- I am not sure about this one, but at least it doesn't require importing an Internal module.
resourceC ::
  Monad m =>
  (InternalState -> ConduitT i o m b) -> ConduitT i o (ResourceT m) b
resourceC k = do
  s <- lift getInternalState
  transPipe lift (k s)
```

Now we can "lift conduits" in the way we are used to from `MonadTrans` instances. The boilerplate for our pass-through typeclass instances now reduces to:

```haskell
class Monad m => MonadFileSystem m where
  sourceFile :: FilePath -> ConduitT i ByteString m ()
  sinkFile :: FilePath -> ConduitT ByteString o m ()

  default sourceFile :: (MonadCTrans t, MonadFileSystem m', t m' ~ m) => FilePath -> ConduitT i ByteString m ()
  sourceFile = clift . sourceFile
  default sinkFile :: (MonadCTrans t, MonadFileSystem m', t m' ~ m) => FilePath -> ConduitT ByteString o m ()
  sinkFile = clift . sinkFile

instance MonadFileSystem m => MonadFileSystem (IdentityT m)
instance MonadFileSystem m => MonadFileSystem (MaybeT m)
instance MonadFileSystem m => MonadFileSystem (ReaderT r m)
instance MonadFileSystem m => MonadFileSystem (ExceptT e m)
instance (Monoid w, MonadFileSystem m) => MonadFileSystem (WriterT w m)
instance MonadFileSystem m => MonadFileSystem (StateT s m)
instance MonadFileSystem m => MonadFileSystem (ResourceT m)
```

In similar spirit, the `combined` function from above would be written as

```haskell
combined = clift conduit1 .| conduit2
```

Do you think something like this would be useful?

**Comment by mbwgh** [comment]
Now that I think about it some more, this is very similar to the old `MFunctor` instance, only less general.

**Comment by snoyberg** [comment]
I believe the `transPipe` function provides what you're looking for.

**Comment by mbwgh** [comment]
And I believe you are right. I was looking for `transPipe lift`, `transPipe (lift . lift)` et cetera, which would correspond to my `clift` and `clift . clift`. This is good news.

I was deterred by the way the `transPipe` function is currently documented. I was well aware of this function, but the haddocks, wiki entry and blog post make it seem like you "should stay away from it" and use the `Data.Conduit.Lift` module instead. Even though strictly speaking this module isn't really about lifting at all (in the narrow sense of using `lift`). In particular, and that is actually pointed out in the blog post but I missed it, using `transPipe lift` is safe.

Care for a doc patch (or maybe even a `liftC = transPipe lift`, since that may just be the most common usage)?

**Comment by snoyberg** [comment]
Doc patch would be great, thanks. And for the record, `transPipe` is a really bad name, especially since `Pipe` is now a hidden internal of the library, so better names as a synonym would be welcome as well.

**Comment by mbwgh** [comment]
On first intuition, `transPipe` seems to be a type-restricted version of `hoist`, so `hoistC` comes to mind. But that probably wouldn't perfectly fit the bill, since some thought was put into what a `C` suffix should stand for - I believe I saw a doc patch regarding this somewhere as well.

In the previous version of my comment I suggested a `liftC = transPipe lift` as well, but quickly edited it away, under the assumption that `transPipe (lift . lift)` would be more efficient than `transPipe lift . transPipe lift`. There  may even be some subtle semantic difference?

In any case, would you like to deprecate `transPipe`?

**Comment by snoyberg** [comment]
hoistC sounds fine, I don't understand your objections. I don't want to
deprecate transPipe yet, it will be useful for easy backwards compatibility.

**Comment by mbwgh** [comment]
I read through #383 again and indeed my doubts were unfounded - I merely thought that `C` not only implied returning a `ConduitT`, but some specific relation to a non-conduit function as well.

The only issue I see is that people will ask "why not just add an `MFunctor` instance". Am I right to assume the reason for dropping the `mmorph` dependency was that the monad transformer laws cannot be upheld for every choice of first argument, the `(forall a. m a -> n a)`? If so, the suggestive name `hoistC` may warrant a short comment about that as well.

**Comment by snoyberg** [comment]
It was because there's been ongoing discussion in that package of changing
the typeclass definition in such a way that would make hoist much slower
for conduit (and yes, it's related to the issue of laws being upheld).

**Comment by mbwgh** [comment]
Okay, I will submit a PR then. Closing since my initial question has been answered (thanks by the way).
