### ISSUE TITLE
Differences between catchC and catch

### ISSUE THREAD

**Issue by mbwgh** [snoyberg/conduit#391]
When working with `conduit` you necessarily have three different `catch` functions available: `Data.Conduit.catchC`, `UnliftIO.Exception.catch` and `Control.Exception.catch`.

These functions differ in how they treat asynchronous exceptions, and `catchC` uses `Control.Exception.catch` internally.

There is however one other major caveat, namely the masking state, or rather what happens to it when we tail-call from inside an exception handler. I tried to find out how `catchC` behaves in this regard:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE LambdaCase #-}
module ExceptionTest where

import Control.Monad (unless)
import Control.Exception (getMaskingState)

import Conduit
import UnliftIO

data Number = One | Two | Three deriving (Eq, Ord, Show, Enum, Bounded)

yieldNumbers :: ConduitT i Number IO ()
yieldNumbers = do
  nRef <- newIORef One
  liftIO (getMaskingState >>= print)
  let loop = do
        n <- readIORef nRef
        yield n
        modifyIORef' nRef succ
        loop
  loop `catchC` \(e :: SomeException) -> do
    liftIO . putStrLn $ "Encountered error: " ++ displayException e
    liftIO . putStrLn $ "Starting from scratch..."
    yieldNumbers

testNumbers :: IO ()
testNumbers = runConduit $ yieldNumbers .| takeC 10 .| printC

yieldNumbers2 :: IORef Int -> IO ()
yieldNumbers2 counterRef = do
  nRef <- newIORef One
  getMaskingState >>= print
  let loop = do
        readIORef nRef >>= print
        modifyIORef' nRef succ
        counter <- readIORef counterRef
        modifyIORef' counterRef succ -- If we forget this, UserInterrupt may not help.
        unless (counter >= 10) loop
  loop `catch` \(e :: SomeException) -> do
    liftIO . putStrLn $ "Encountered error: " ++ displayException e
    liftIO . putStrLn $ "Starting from scratch..."
    yieldNumbers2 counterRef

testNumbers2 :: IO ()
testNumbers2 = do
  counterRef <- newIORef 0
  yieldNumbers2 counterRef

yieldNumbers3 :: IORef Int -> IO ()
yieldNumbers3 counterRef = do
  nRef <- newIORef One
  getMaskingState >>= print
  let loop = do
        readIORef nRef >>= print
        modifyIORef' nRef succ
        counter <- readIORef counterRef
        modifyIORef' counterRef succ
        unless (counter >= 10) loop
  try loop >>= \case
    Left (e :: SomeException) -> do
      putStrLn $ "Encountered error: " ++ displayException e
      putStrLn "Starting from scratch..."
      yieldNumbers3 counterRef
    Right () -> return ()

testNumbers3 :: IO ()
testNumbers3 = do
  counterRef <- newIORef 0
  yieldNumbers3 counterRef
```

`testNumbers2` and `testNumbers3` use `catch` and `try` from `UnliftIO` and behave like their `Control.Exception` counterparts: A tail-call from `catch` will happen while in a masked state (which is probably undesirable), while `try` will happen in an unmasked state.

However, `testNumbers`, using `catchC`, will re-enter `Unmasked`.
Is this actually how `catchC` behaves, or did I just fail to come up with a misbehaving example? If it is true, is it by design or by accident? Should it be documented? Might there be cases were this behavior is not what we want?

**Comment by snoyberg** [comment]
These functions are inherently different due to conduit using coroutines
under the surface. There are a lot of details in this issue. Can you
clarify what your actual question is?

**Comment by mbwgh** [comment]
Maybe I should have left out the code example. The question is in the last paragraph of my previous comment. By "this" and "it", I was referring to the behavior described [in the Control.Exception documentation](http://hackage.haskell.org/package/base-4.11.1.0/docs/Control-Exception.html#g:3), namely

> The difference between using try and catch for recovery is that in catch the handler is inside an implicit mask[...]. Furthermore it is possible to accidentally stay inside the implicit mask by tail-calling rather than returning from the handler, which is why we recommend using try rather than catch for ordinary exception recovery.

**Comment by snoyberg** [comment]
No, it does not mask exceptions in the tail call.
