### ISSUE TITLE
Question : can we serialize sources into one ?

### ISSUE THREAD

**Issue by nhenin** [snoyberg/conduit#393]
Hi, I'm looking for a function that could have this signature : 
`serializeSources :: Monad m => [Source m a] -> Source m a`
Having x sources with the same value produced that are serialized into 1 stream, Sorry in advance if you have already a function for that but I didn't find it... ZipSources would be the closest that I have found but I don't want the "zipList" behaviour as you can imagine in my context ...
Thank you ! 
P.S : Except ZipXXX, I still trying to understand how I can perform parallel/concurrent streaming etc.. with the library

**Comment by nhenin** [comment]
I've just discovered https://github.com/cgaebel/stm-conduit, with the mergeSources function... It looks  like this is what I was looking for... some feedbacks : Somehow it was not clear in my head when I read the doc that the basic packages of conduit was not really dealing with multithreading :-)

**Comment by snoyberg** [comment]
PR welcome to improve the docs, but I'm not sure if there's anything left to discuss in this issue.

**Comment by nhenin** [comment]
yeah there is nothing left to discuss  :-)
