### ISSUE TITLE
resourcet-1.2.2 deprecation warning.

### ISSUE THREAD

**Issue by Magicloud** [snoyberg/conduit#395]
GHC 8.6.1.

```
[2 of 5] Compiling Control.Monad.Trans.Resource.Internal ( Control/Monad/Trans/Resource/Internal.hs, dist/build/Control/Monad/Trans/Resource/Internal.o )

Control/Monad/Trans/Resource/Internal.hs:43:1: warning: [-Wdeprecations]
    Module ‘Control.Monad.Trans.List’ is deprecated:
      This transformer is invalid on most monads
   |
43 | import Control.Monad.Trans.List     ( ListT    )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Control/Monad/Trans/Resource/Internal.hs:264:46: warning: [-Wdeprecations]
    In the use of type constructor or class ‘ListT’
    (imported from Control.Monad.Trans.List):
    Deprecated: "This transformer is invalid on most monads"
    |
264 | GO(ListT)
    |                                              ^^^^^
```

**Comment by snoyberg** [comment]
We're not using it, just providing an instance for it. It doesn't present any problems for conduit.

**Comment by Magicloud** [comment]
I see. But since there is a -Wall, this blocks things from building.

**Comment by snoyberg** [comment]
Wall does not prevent a build, it causes warnings.

**Comment by Magicloud** [comment]
Hum, I think it caused all warning to error. I commented the line in .cabal locally, and it now builds.

**Comment by Magicloud** [comment]
Interesting. I commented this line locally and got this package built. But hackage version stopped with this warning.

**Comment by Magicloud** [comment]
Sorry. I meant when I used cabal-install to install the package. Just did a clear test to install only resourcet-1.2.2, passed.

I cannot remember which package I was installing depended on resourcet. Seems like that package set -Werror so warning in resourcet failed the whole process.

**Comment by snoyberg** [comment]
If that indeed happened, it's a bug in cabal-install. However, is it
possible you passed it on the command line instead?

**Comment by Magicloud** [comment]
I did not have special params passed. Anyway, let me close this for now and try to reproduce the issue first. Thanks for your time.

**Comment by Magicloud** [comment]
Seems like it is an issue with cabal-install. Not spreading Werror, but silent fail without proper messages. The "block building" was caused by other package, but cabal-install only shows resourcet's warning.
