### ISSUE TITLE
Question about zipping conduits

### ISSUE THREAD

**Issue by sergey-kintsel** [snoyberg/conduit#396]
I've got an interesting (as for me) problem. I have 2 sorted sources of JSON (they are sorted by Int id field). I need to find the ones which do not exist in either of sources OR which have different hashes inside. I've got a solution. Basically, it takes values from both sources, compares them, if they have the same ID then it compares the contents, if 1st is less than the 2nd then it's an error and I return the 2nd to the stream, the opposite for the case when 2nd is less than the 1st: 
```haskell
compareSources :: Monad m => Source m Document -> Source m Document -> Source m Inconsistency
compareSources oldSource newSource =
  go (newResumableSource oldSource) (newResumableSource newSource)
  where
    go :: Monad m => ResumableSource m Document -> ResumableSource m Document -> Source m Inconsistency
    go oldRSource newRSource = do
      (oldRSource', maybeOldDoc) <- lift $ oldRSource $$++ await
      (newRSource', maybeNewDoc) <- lift $ newRSource $$++ await
      case (maybeOldDoc, maybeNewDoc) of
        (Nothing, Nothing) -> clearResources
        (Just oldDoc, Just newDoc) ->
          case compare (documentId oldDoc) (documentId newDoc) of
            EQ -> yieldMany (compareDocs oldDoc newDoc) >> proceedToNextPair
            LT -> yield (missing oldDoc) >> returnNewDocToStream
            GT -> yield (unknown newDoc) >> returnOldDocToStream
          where
            returnOldDocToStream = go oldRSource newRSource'
            returnNewDocToStream = go oldRSource' newRSource
            proceedToNextPair = go oldRSource' newRSource'
        (Just oldDoc, Nothing) -> yield $ missing oldDoc
        (Nothing, Just newDoc) -> yield $ unknown newDoc
      where
        clearResources = do
          lift $ closeResumableSource oldRSource
          lift $ closeResumableSource newRSource
          return ()
        missing doc = MissingDocument (documentType doc) (documentId doc)
        unknown doc = UnknownDocument (documentType doc) (documentId doc)
``` 
I am strongly convinced that I'm doing something (maybe everything) wrong and I bet there is a better way to handle this thingy.

Thanks for reading and, hopefully, for help 😃
P.S. it uses outdated ResumableSource, there is a SealedConduitT atm, but I don't wanna migrate it before I know that this solution is worth it

**Comment by snoyberg** [comment]
Only problem I see is the reusing of the original `oldRSource` and `newRSource` values. This looks like a case which should be addressed nicely by `ZipSource`, but given that you'll need to consume the two `Source`s at different rates I don't think it will work out.

Using `SealedConduitT` will likely make this quite a bit easier, as you don't need to futz around with finalizers.

**Comment by sergey-kintsel** [comment]
Thank you very much! :-)
