### ISSUE TITLE
`Win32` isn't present in the auto-generated global-hints.yaml

### ISSUE THREAD

**Issue by sgraf812** [snoyberg/conduit#399]
#45 seems to trigger again for `ghc-8.6.3`. Can you think of some automated way to derive the version of `Win32` that ships with a certain GHC release, so that we can fix update-global-hints.hs?

**Comment by sgraf812** [comment]
Maybe the tool could parse https://downloads.haskell.org/~ghc/$ghcVer/docs/html/users_guide/$ghcVer-notes.html#included-libraries instead? Or at least scrape the Win32 version from there.

**Comment by snoyberg** [comment]
I think this is the wrong issue tracker.

**Comment by sgraf812** [comment]
Certainly! Ouch. I wonder how I ended up here
