### ISSUE TITLE
Feature Request: sourceVector

### ISSUE THREAD

**Issue by bbarker** [snoyberg/conduit#401]
`sinkVector` exists, but `sourceVector` does not seem to exist in any form, currently.

**Comment by snoyberg** [comment]
[`yieldMany`](https://www.stackage.org/haddock/lts-13.2/conduit-1.3.1/Data-Conduit-Combinators.html#v:yieldMany) should do the trick.

**Comment by bbarker** [comment]
Right you are, thanks!
