### ISSUE TITLE
Why were the MonadBase and MonadBaseControl instances removed from resourcet-1.2.0?

### ISSUE THREAD

**Issue by shlok** [snoyberg/conduit#404]
In resourcet-1.1.11, we used to have the instances

    MonadBase b m => MonadBase b (ResourceT m)
    MonadBaseControl b m => MonadBaseControl b (ResourceT m)

Why were these removed in resourcet-1.2.0?

(I came across a situation where having the instances could have been useful: [`withMergedStreams` of Streaming.Concurrent](https://hackage.haskell.org/package/streaming-concurrency-0.3.1.2/docs/Streaming-Concurrent.html#g:3) requires these instances.)

**Comment by snoyberg** [comment]
Please see https://www.snoyman.com/blog/2018/02/conduitpocalypse

**Comment by shlok** [comment]
Thanks!
