### ISSUE TITLE
resourcet: resourceForkWith fails to run cleanup actions when used with linked Asyncs

### ISSUE THREAD

**Issue by infinity0** [snoyberg/conduit#415]
```haskell
module Main where

import Control.Concurrent
import Control.Concurrent.Async
import Control.Monad
import Control.Monad.IO.Unlift
import Control.Monad.Trans.Resource

resourceForkWith' :: MonadUnliftIO m => (IO () -> IO a) -> ResourceT m () -> ResourceT m a
resourceForkWith' g r = withRunInIO $ \run -> g $ run r

main :: IO ()
main = runResourceT $ do
  liftIO $ putStrLn "starting test... press ctrl-c in the next 10s"
  resourceForkWith (link <=< async) $ liftIO $ do
    threadDelay 10000000
  allocate (pure ()) $ \_ -> do
    putStrLn "destroyed called"
  liftIO $ threadDelay 10000000
```

Actual behaviour:
~~~~
$ ghc ./Test.hs  && ./Test
Loaded package environment from $PWD/.ghc.environment.x86_64-linux-8.6.4
[1 of 1] Compiling Main             ( Test.hs, Test.o )
Linking Test ...
starting test... press ctrl-c in the next 10s
^C
exit code 130
~~~~

Expected behaviour (and actual behaviour when using the dummy `resourceForkWith'`):
~~~~
$ ghc ./Test.hs  && ./Test
Loaded package environment from $PWD/.ghc.environment.x86_64-linux-8.6.4
[1 of 1] Compiling Main             ( Test.hs, Test.o )
Linking Test ...
starting test... press ctrl-c in the next 10s
^Cdestroyed called

exit code 130
~~~~

**Comment by snoyberg** [comment]
This is expected behavior. There's no way to know if the resources are being used by the child thread, which is still running.

**Comment by infinity0** [comment]
@snoyberg All child threads die eventually, yet the destructor never gets called when that happens.

**Comment by infinity0** [comment]
Actually, the bug seems to be present even if I use `forkIO` instead of `link <=< async`.

**Comment by infinity0** [comment]
OK, perhaps ResourceT is not at fault here. It seems that the main thread gets a haskell async exception triggered by SIGINT and this exits the whole process immediately without giving anything else a chance to run, I guess due to C runtime rules or something. I'll try to confirm this.

**Comment by infinity0** [comment]
The underlying problem can be reproduced without using ResourceT and is fixed by manually tracking child threads and waiting for them after catching an exception in the main thread similar to described [here](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Concurrent.html#g:12).

```haskell
main :: IO ()
main = do
  liftIO $ putStrLn "starting test... press ctrl-c in the next 10s"
  forkIO $ bracket (pure ())
                 (\_ -> putStrLn "cleanup called")
                 (\_ -> threadDelay 10000000)
  liftIO $ threadDelay 10000000
```

Therefore, closing this bug.
