### ISSUE TITLE
takeE

### ISSUE THREAD

**Issue by XinhuaZhang** [snoyberg/conduit#422]
I would like to read a binary file and to create a conduit that outputs a n-byte bytestring every time the conduit after it fetches one. I used Data.Conduit.Combinator. Suppose the handle is h, this is how I construct the conduit.

sourceHandle h .| takeE n

I am not sure if this is the right way to use takeE.

**Comment by snoyberg** [comment]
I think chunksOfE will do what you want https://www.stackage.org/haddock/nightly-2019-10-20/conduit-1.3.1.1/Data-Conduit-Combinators.html#v:chunksOfE

**Comment by XinhuaZhang** [comment]
> I think chunksOfE will do what you want https://www.stackage.org/haddock/nightly-2019-10-20/conduit-1.3.1.1/Data-Conduit-Combinators.html#v:chunksOfE

Thanks!
