### ISSUE TITLE
There doesn't seem to be a way to specify TLS Client Configs

### ISSUE THREAD

**Issue by dustin** [snoyberg/conduit#423]
`TLSClientConfig` fields aren't exported and I'd like to specify `TLSSettings` for a connection.  Is there a way to do this I don't see, or can this be exported?

**Comment by snoyberg** [comment]
It's a weird trick that I don't like anymore, and Haddock doesn't display it correctly. But the fields are exported, just not the data constructor. See, for example, [`tlsClientPort`](https://www.stackage.org/haddock/lts-14.11/network-conduit-tls-1.3.2/Data-Conduit-Network-TLS.html#v:tlsClientPort).

**Comment by dustin** [comment]
Thanks.  I do believe this works for me.  It compiles anyway.  :)  I did see the fields there, but didn't read them that way.  So I also learned something.
