### ISSUE TITLE
Conduit with RecursiveDo

### ISSUE THREAD

**Issue by onixie** [snoyberg/conduit#428]
I have a usecase that I need to send the output from the downstream back to the input of upstream? I came up an idea to use MonadFix/RecursiveDo syntax, but it seems it doesn't work.
for example, the following piece of code issues an cyclic evaluation error instead of returning an infinite list.

```
ones' :: IO [Int]
ones' = mdo
  n <- runConduit $ yieldMany (1:n) .| sinkList
  return n
```

```
λ> ones'
*** Exception: cyclic evaluation in fixIO
```

Just asking, is it possible to do this with RecursiveDo? or if there is any other way to feed the output from downstream back to upstream?

**Comment by snoyberg** [comment]
Sounds like something I may use a TBQueue for.

**Comment by onixie** [comment]
I figured out something like the following and solved my problem. Thank you for the advice. 
```
feedback :: MonadIO m => i -> ConduitT i i m r -> ConduitT () i m r
feedback init conduit = do
    out <- liftIO $ newTBQueueIO 1
    ret <- liftIO $ newIORef undefined
    lst <- liftIO $ newIORef undefined
    liftIO $ atomically $ writeTBQueue out init
    recv out .| (conduit >>= liftIO . writeIORef ret) .| send lst out
    liftIO (readIORef lst) >>= yield
    liftIO (readIORef ret)
  where
    recv out = do
      v <- liftIO . atomically $ readTBQueue out
      yield v
      recv out
    send lst out = awaitForever $ \i -> liftIO $ do
      writeIORef lst i
      atomically $ writeTBQueue out i
```
