### ISSUE TITLE
createSink sets up process forever awaiting data on stdin

### ISSUE THREAD

**Issue by pbrisbin** [snoyberg/conduit#434]
I'm trying to write an application that streams (via conduit) from *and to* `tar` processes (via typed-process). I found that streaming `stdout` works fine, but when I stream to `stdin`, the process never exits, it always awaits more data.

Here's a minimal repro:

```hs
module Main
  ( main
  )
where

import RIO

import Conduit
import Data.Conduit.Process.Typed (createSink, createSource)
import RIO.Process

main :: IO ()
main = runSimpleApp $ runResourceT $ do
  tmp <- proc "echo" ["Hello World"] $ withStreamingStdout_ $ sinkSystemTempFile
    "hello-world"

  -- Worked fine
  current <- readFileUtf8 tmp
  logInfo $ displayShow tmp <> ": " <> displayShow current

  -- But this sits forever, because nothing tells cat that stdin won't receive
  -- more data after the Source runs outs. Why?
  proc "cat" [] $ withStreamingStdin_ $ sourceFile tmp

withStreamingStdout_
  :: MonadUnliftIO m
  => ConduitT ByteString Void m a
  -> ProcessConfig stdin stdout stderr
  -> m a
withStreamingStdout_ sink pc = withUnliftIO $ \u -> do
  let pc' = setStdout createSource pc

  withProcessWait pc' $ \p -> do
    a <- unliftIO u $ runConduit $ getStdout p .| sink
    a <$ checkExitCode p

withStreamingStdin_
  :: MonadUnliftIO m
  => ConduitT () ByteString m ()
  -> ProcessConfig stdin stdout stderr
  -> m ()
withStreamingStdin_ source pc = withUnliftIO $ \u -> do
  let pc' = setStdin createSink pc

  withProcessWait pc' $ \p -> do
    unliftIO u $ runConduit $ source .| getStdin p
    checkExitCode p
```

The conduit does run and the source data (`"Hello World\n"`) is printed by the `cat`, but then it just hangs awaiting more. It never sees end-of-file.

I guess this makes sense, and I assume I need to signal it somehow? Generally, how is one supposed to accomplish streaming to a process' stdin with these tools?

**Comment by snoyberg** [comment]
I think we need to add a `createSinkClose` or similar function, which not only includes the sink, but a function to close the handle. I've added this on `master` in 1571cdff47eba766cb83277d7df2b6a6e9e0ae05, can you give this a shot and see if it fixes your case?

**Comment by pbrisbin** [comment]
It worked!

<details>
<summary>Updated, now-functioning repro</summary>

```hs
module Main
  ( main
  )
where

import RIO

import Conduit
import Data.Conduit.Process.Typed (createSource)
import RIO.Process

main :: IO ()
main = runSimpleApp $ runResourceT $ do
  tmp <- proc "echo" ["Hello World"] $ withStreamingStdout_ $ sinkSystemTempFile
    "hello-world"

  -- Worked fine
  current <- readFileUtf8 tmp
  logInfo $ displayShow tmp <> ": " <> displayShow current

  -- But this sits forever, because nothing tells cat that stdin won't receive
  -- more data after the Source runs outs. Why?
  proc "cat" [] $ withStreamingStdin_ $ sourceFile tmp

withStreamingStdout_
  :: MonadUnliftIO m
  => ConduitT ByteString Void m a
  -> ProcessConfig stdin stdout stderr
  -> m a
withStreamingStdout_ sink pc = withUnliftIO $ \u -> do
  let pc' = setStdout createSource pc

  withProcessWait pc' $ \p -> do
    a <- unliftIO u $ runConduit $ getStdout p .| sink
    a <$ checkExitCode p

withStreamingStdin_
  :: MonadUnliftIO m
  => ConduitT () ByteString m ()
  -> ProcessConfig stdin stdout stderr
  -> m ()
withStreamingStdin_ source pc = withUnliftIO $ \u -> do
  let pc' = setStdin createSinkClose pc

  withProcessWait pc' $ \p -> do
    let (sink, close) = getStdin p
    unliftIO u $ runConduit $ source .| sink
    close
    checkExitCode p

createSinkClose
  :: (MonadIO m, MonadIO n)
  => StreamSpec 'STInput (ConduitM ByteString o m (), n ())
createSinkClose =
  (\h ->
      (liftIO (hSetBuffering h NoBuffering) >> sinkHandle h, liftIO (hClose h))
    )
    `fmap` createPipe
```

</details>

Usage is a bit awkward:

```hs
withStreamingStdin_
  :: MonadUnliftIO m
  => ConduitT () ByteString m ()
  -> ProcessConfig stdin stdout stderr
  -> m ()
withStreamingStdin_ source pc = withUnliftIO $ \u -> do
  let pc' = setStdin createSinkClose pc

  withProcessWait pc' $ \p -> do
    let (sink, close) = getStdin p
    unliftIO u $ runConduit $ source .| sink
    close
    checkExitCode p
```

I wish there were a way to do it that didn't require I call the `close` function myself, that seems risky. 

I tried this:

```hs

withStreamingStdin_
  :: MonadUnliftIO m
  => ConduitT () ByteString m ()
  -> ProcessConfig stdin stdout stderr
  -> m ()
withStreamingStdin_ source pc = withUnliftIO $ \u -> do
  let pc' = setStdin createSink pc

  withProcessWait pc' $ \p -> do
    unliftIO u $ runConduit $ source .| getStdin p
    checkExitCode p

createSink :: (MonadIO m) => StreamSpec 'STInput (ConduitM ByteString o m ())
createSink =
  (\h -> liftIO (hSetBuffering h NoBuffering) >> sinkHandleClose h)
    `fmap` createPipe

sinkHandleClose h = do
  mVal <- await
  case mVal of
    Nothing -> hClose h
    Just val -> do
      liftIO $ BS.hPut h val
      sinkHandle h

```

But it similarly hangs forever. I guess the `await` never returns `Nothing`? I'm a bit of a conduit novice, so it doesn't make conceptual sense to me why you can't rely on a `Nothing` out of `await` to signify the end of the stream and take the close action then.

Assuming we do need `createSinkClose`, I'm curious when `createSink` is ever useful -- it feels like a foot-gun to me. Maybe a path of deprecation and renaming `createSinkClose -> createSink` would be a good idea?

**Comment by snoyberg** [comment]
I think in your `sinkHandleClose`, you need to replace the recursive call to use `sinkHandleClose` instead of `sinkHandle`. That approach may work though. Can you try the latest version on `master`?

**Comment by pbrisbin** [comment]
:man_facepalming: oh geeze,  I guess that's what you get when the types don't save you.

Yes, with that fix my `sinkHandleClose` works, and the world makes sense again. I also tested your `createSinkClose` from `master` and that worked too. Thanks for the quick fixes.

Is there a reason you prefer that approach of doing it directly in `createSinkClose`, instead of introducing `sinkHandleClose` like I did? Is a version of `sinkHandle` that closes not itself generally useful?

**Comment by snoyberg** [comment]
Nah, not really any reason for the preference, it seemed easiest to make a minor tweak to the existing function. Do you have a concern with it?

**Comment by pbrisbin** [comment]
Not at all, just trying to learn the reasoning.

**Comment by snoyberg** [comment]
No deep reasoning :D

**Comment by snoyberg** [comment]
conduit-extra-1.3.5 released
