### ISSUE TITLE
Separate expressions for easier comparison in README

### ISSUE THREAD

**Issue by masaeedu** [snoyberg/conduit#439]
Hello there. Thanks for putting together the very comprehensive README for this project. I'm going through that right now, and it's very nice to see a project that presents the underlying concepts of the library in a steady progression.

As a minor nit, I feel that examples like this:

```haskell
main :: IO ()
main = do
    putStrLn "List version:"
    print $ take 10 [1..]
    putStrLn ""
    putStrLn "Conduit version:"
    print $ runConduitPure $ yieldMany [1..] .| takeC 10 .| sinkList
```

Would scan a little bit better if they were written like this:

```haskell
take10List :: IO ()
take10List =
  print $ take 10 [1..]

take10Conduit :: IO ()
take10Conduit =
  print $ runConduitPure $ yieldMany [1..] .| takeC 10 .| sinkList

main :: IO ()
main = do
    putStrLn "List version:"
    take10List

    putStrLn ""
    putStrLn "Conduit version:"
    take10Conduit
```

This wastes more lines, but IMO it's easier to demarcate where one example ends and the other begins, and to compare the differences between them.

What do you think? If you want, I can make a PR to tweak this.

**Comment by snoyberg** [comment]
Sounds great, thanks! PR welcome
