### ISSUE TITLE
Provide `uncons`

### ISSUE THREAD

**Issue by kirelagin** [snoyberg/conduit#442]
There is a more-or-less standard pattern:

```haskell
Y.unfoldM X.uncons
```

which can be used to convert a stream from a streaming library `X` to a streaming library `Y`. However, `conduit` doesn’t seem to provide `uncons` or any way of implementing it.

**Comment by snoyberg** [comment]
I'm not opposed to such an addition, PR welcome

**Comment by kirelagin** [comment]
As a small update, I implemented `uncons` for `Pipe` without any issues, but now I am deeply stuck trying to implement it for `ConduitT`. The problem is that I need to unwrap the `ConduitT`, but then I am left with a `Pipe`, which represents the tail, but I need to somehow wrap it back into a conduit, and I don’t quite understand how to do this (and if it is possible at all).

Here is what I have:

```haskell
uncons
  :: forall m o conduit.  (Monad m, conduit ~ ConduitT () o m ())
  => conduit -> m (Maybe (o, conduit))
uncons (ConduitT p) = go $ injectLeftovers $ p Done
  where
    go :: Pipe Void () o () m () -> m (Maybe (o, conduit))
    go (HaveOutput more o) = pure $ Just (o, ConduitT $ \rest -> _HMMMMM)
    go (NeedInput _ c) = go (c ())
    go (Done ()) = pure Nothing
    go (PipeM mp) = mp >>= go
    go (Leftover _ i) = absurd i
```

**Comment by snoyberg** [comment]
For future reference, it would be a good idea to include the error message the compiler gives you for this kind of code.

The easiest way to fix this is to not pin the leftover type paramter to `Void`. Instead, let it unify with the input type parameter, which is what the `ConduitT` type itself is doing. Then instead of using `absurd`, you can just ignore the leftovers. Example:

```haskell
uncons
  :: forall m o conduit.  (Monad m, conduit ~ ConduitT () o m ())
  => conduit -> m (Maybe (o, conduit))
uncons (ConduitT p) = go $ injectLeftovers $ p Done
  where
    go :: Pipe () () o () m () -> m (Maybe (o, conduit))
    go (HaveOutput more o) = pure $ Just (o, ConduitT $ \rest -> more >>= rest)
    go (NeedInput _ c) = go (c ())
    go (Done ()) = pure Nothing
    go (PipeM mp) = mp >>= go
    go (Leftover p ()) = go p
```

I think that behaves the way you want.

**Comment by kirelagin** [comment]
Oh, I see, thank you!

I guess, my main problem is that I do not understand `conduit` well enough to be able to confidently say that it is ok to ignore the leftover in this case. So I took that type error as an indicator that I genuinely did something wrong.

One other thing that makes me worry is that I am injecting leftovers on every call to `uncons` – I am not sure if it is a good idea or a bad one, given that `uncons` is meant to be called iteratively after each element of the stream arrives.

**Comment by snoyberg** [comment]
Ignoring leftovers after `injectLeftovers` is fine. There cannot be any. That's what the `absurd` demonstrates. You can also include an `error` or `assert False` in the `Leftover` case if you wanted.

Injecting leftovers each time is probably fine, it's performing a bit of bookkeeping to hold onto leftovers for later steps. It's probably not idea though: sticking with the `Pipe` structure for a series of `uncons` calls would make a lot more sense.
