### ISSUE TITLE
Is chunksOfExactlyE correct in the case of an empty input chunk?

### ISSUE THREAD

**Issue by tilk** [snoyberg/conduit#445]
If I'm reading the definition of `chunksOfExactlyE` correctly, on the case `onull b` -- which means that the input chunk was empty -- `chunksOfE` will be called, changing the behavior to that of `chunksOfE` (with the remainder yielded and not left over). Am I reading this correctly? Is this the intended behavior for some reason, or is it a bug?

**Comment by snoyberg** [comment]
Yup, it looks like a bug. Interested in sending a PR?

**Comment by tilk** [comment]
I sent a PR (#446).

**Comment by snoyberg** [comment]
Thanks!
