### ISSUE TITLE
Deprecation warnings when building as dependency with Stack

### ISSUE THREAD

**Issue by brightly-salty** [snoyberg/conduit#449]
When building a package with resourcet as a dependency with 'stack build', I got the following deprecation warnings. I thought this would be the right place to post such an issue, although I do not have any interest in fixing it.

resourcet            > /private/var/folders/6v/2dmhwn3x0dxcggh8jzbh30tw0000gn/T/stack-310748297c065aed/resourcet-1.2.4.2/Control/Monad/Trans/Resource/Internal.hs:43:1: warning: [-Wdeprecations]
resourcet            >     Module ‘Control.Monad.Trans.List’ is deprecated:
resourcet            >       This transformer is invalid on most monads
resourcet            >    |
resourcet            > 43 | import Control.Monad.Trans.List     ( ListT    )
resourcet            >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
resourcet            >

resourcet            > /private/var/folders/6v/2dmhwn3x0dxcggh8jzbh30tw0000gn/T/stack-310748297c065aed/resourcet-1.2.4.2/Control/Monad/Trans/Resource/Internal.hs:266:46: warning: [-Wdeprecations]
resourcet            >     In the use of type constructor or class ‘ListT’
resourcet            >     (imported from Control.Monad.Trans.List):
resourcet            >     Deprecated: "This transformer is invalid on most monads"
resourcet            >     |
resourcet            > 266 | GO(ListT)
resourcet            >     |

**Comment by snoyberg** [comment]
These aren't a problem, they're providing a legacy instance, and removing them would break backwards compat.
