### ISSUE TITLE
Cleanup of streaming process on exception - withStreamingProcess?

### ISSUE THREAD

**Issue by Martinsos** [snoyberg/conduit#452]
Hi, first thank you for this library, it has greatly simplified dealing with multiple streaming processes at the same time for me (I am using Data.Conduit.Process).

One thing that I got bitten by is that I forgot to terminate the process in case of exception. In my case, I am combining two streaming processes with `Async.race` and if one dies, another one will receive an exception which I forgot to handle, effectively leaving the process running unless I make sure to handle that exception and terminate the process myself.

To achieve this, I ended up using `bracket` + `System.Process.terminateProcess . streamingProcessHandleRaw`, but it took me quite some time to figure out that `terminateProcess` is the right function to use (I am still not sure if `cancelProcess` would be better? But I had trouble obtaining handles to pass to it), and to investigate if there is a better way to do this.

I was especially confused with all the reexporting of the libraries, which made it kind of hard to figure out what to use with what. Should I look for solution in Data.Conduit.Process, or in System.Process, or in Data.Streaming.Process? What is the "right way"? Am I loosing something by using `streamingProcessHandleRaw`?

Just to be clear, I am not complaining in any way, and I am sure my confusion/mistakes were caused by me having superficial knowledge of both Conduit and Process libraries in Haskell, but I am sure there might be more people like me, and since Conduit.Process is so easy to use, I am wondering how to also make it easier to get this part right.

My questions would be:
1. Is approach I used reasonable, or did I miss a better solution?
2. Would it make sense to add `withStreamingProcess` function? Such function would on one hand take care of the whole thing without exposing internals (`streamingProcessHandleRaw`), but it would also make it obvious that handling of the exceptions is important and should be thought of -> it could be a recommended way of creating the streaming process, and `streamingProcess` would remain as an alternative, more flexible approach. If this makes sense and is valuable, I would be happy to try to make a PR for it.

Here is how I used the bracket:
```hs
-- | Runs a given process while streaming its stderr and stdout to provided channel.
--   Returns exit code of the process once it finishes, and also sends it to he channel.
--   Makes sure to terminate the process if exception occurs.
runProcessAsJob :: P.CreateProcess -> J.JobType -> Chan JobMessage -> IO ExitCode
runProcessAsJob process jobType chan = bracket
    (CP.streamingProcess process)
    (\(_, _, _, sph) -> terminateStreamingProcess sph)
    runStreamingProcessAsJob
  where
    runStreamingProcessAsJob (CP.ClosedStream, stdoutStream, stderrStream, processHandle) = do
      let forwardStdoutToChan = runConduit $ stdoutStream .| CL.mapM_
              (\bs -> writeChan chan $ J.JobMessage { J._data = J.JobOutput (BS.unpack bs) J.Stdout
                                                    , J._jobType = jobType })

      let forwardStderrToChan = runConduit $ stderrStream .| CL.mapM_
              (\bs -> writeChan chan $ J.JobMessage { J._data = J.JobOutput (BS.unpack bs) J.Stderr
                                                    , J._jobType = jobType })

      exitCode <- runConcurrently $
          Concurrently forwardStdoutToChan *>
          Concurrently forwardStderrToChan *>
          Concurrently (CP.waitForStreamingProcess processHandle)

      writeChan chan $ J.JobMessage { J._data = J.JobExit exitCode
                                    , J._jobType = jobType }

      return exitCode

    terminateStreamingProcess streamingProcessHandle = do
        let processHandle = CP.streamingProcessHandleRaw streamingProcessHandle
        P.terminateProcess processHandle
        return $ ExitFailure 1
```

Running two of these in parallel via Async.race is not visible here, but what happens is that I run two of these "jobs" with runProcessAsJob and then parallelize them with Async.race.

**Comment by snoyberg** [comment]
Thanks for the kind words here.

Overall, that usage of `bracket` makes perfect sense to me. Overall, I'm not terribly happy with the API here, which is why I've been moving towards what I consider the better API based on typed-process:

[Data.Conduit.Process.Typed](https://www.stackage.org/haddock/lts-16.20/conduit-extra-1.3.5/Data-Conduit-Process-Typed.html)

I realize it's a bit of a cop-out answer to say "please consider using this other API instead." But I agree with most of your concerns here, plus a number of others.

It's probably worth deprecating `Data.Conduit.Process` at this point. I should have considered doing it earlier, but I honestly forgot to think about it once I'd published the new module. Would you mind sharing any impressions you have after looking at the newer module?

**Comment by Martinsos** [comment]
@snoyberg thanks for the answer!

Interesting, I wasn't aware of Data.Conduit.Process.Typed.
Looking at it, it seems like `withLoggedProcess_` would very closely match what I need. I haven't tried it yet, but when I find some time to read about typed-process, I will try switching to it and let you know if there were any struggles.

One thing I can say that with Data.Conduit.Process, what helped a lot, was detailed examples. I never worked with Conduit before and what I needed was just streaming output from process. I did read the Conduit documentation and also Conduit.Process docs, but still, having examples which I can just modify slightly is much easier than trying to put something up yourself when you are using the technology for the first time. Anyway, I am sure you are aware of this :), but wanted to emphasize how useful that was -> docs are half of the job (and you did great job with them in Conduit and Conduit.Process).

**Comment by snoyberg** [comment]
Agreed. Next time I have time/energy to do this, I should rewrite the tutorial to use the Typed module.
