### ISSUE TITLE
Deallocation order of ResourceT

### ISSUE THREAD

**Issue by kim** [snoyberg/conduit#46]
I just recently learned that resources are deallocated strictly in FIFO order when `runResourceT` terminates, which is exactly the opposite of what I expected and would need for my project.

I'm not entirely clear on what the reasoning behind this was, and would appreciate if there was a way to specify LIFO deallocation if desired. It's not immediately obvious to me, however, how `resourceForkIO` could be kept consistent with it's enclosing `ResourceT`.

Do you see a way to provide such a feature, or have any concerns?

**Comment by bitc** [comment]
Is deallocation order still guaranteed to be LIFO?

The code has radically changed since 0e3eb31e4cfa425da1bab2c48a394bca250ae102, and it is not mentioned anywhere in the docs, nor do I see any tests that verify this property.

Thank you!

**Comment by snoyberg** [comment]
I believe it is still guaranteed, but you're right about the tests.
Interested in sending a PR to add one?
