### ISSUE TITLE
Folding over Conduit with another Conduit

### ISSUE THREAD

**Issue by brandon-leapyear** [snoyberg/conduit#464]
I'm not sure if I'm missing something obvious, but I'm looking for a function like
```hs
foldConduit :: (i -> s -> ConduitT i o m s) -> s -> ConduitT i o m s
```
If you squint, it looks similar to `foldlM`, except instead of taking in a `t a`, we want to consume objects from the Conduit input.

With my use-case described below, I was thinking of doing something like
```hs
batchesOfC :: Int -> ConduitT Text [Text] m ()
batchesOfC size = do
  lastBuf <- foldConduit go []
  unless (null lastBuf) $ yield $ reverse lastBuf
  where
    go x buf = do
      let buf' = x:buf 
      if sum (map length buf') < size
        then return buf'
        else yield (reverse buf) >> return [x]
```
How can I implement this with the existing Conduit API? Would it be worth adding a function like `foldConduit` to the conduit library like this? I'm willing to make a PR!

## Use case

My use-case is trying to batch elements like `chunksOfCE`, except keeping the elements in a list instead of flattening them. e.g.
```hs
runConduit $
  yieldMany ["a", "bc", "d", "e", "f", "g", "hijk"]
    .| batchesOfC 3 -- ???
    .| sinkList
=>
[["a", "bc"], ["d", "e", "f"], ["g"], ["hijk"]]
```
whereas `chunksOfCE` would return
```hs
runConduit $
  yieldMany ["a", "bc", "d", "e", "f", "g", "hijk"]
    .| chunksOfCE 3
    .| sinkList
=>
["abc","def","ghi","jk"]
```
Notice the keeping of the original elements, but also notice that `hijk` should be kept in a single element. So roughly speaking, the algorithm could be described as:
1. Map every element to a list of one element
2. Start from the left and merge lists leftward if the new group's cumulative length is less than the provided size

**Comment by snoyberg** [comment]
I don't think there's an existing function that does exactly what you're describing, and I'm not certain it would be a general enough concept to include (though I'm not inherently opposed). If I'm reading this correctly, implementing foldConduit would look something like this:

```haskell
foldConduit go accum = do
  mnext <- await
  case mnext of
    Nothing -> pure accum
    Just next -> do
      accum <- go next accum
      foldConduit go accum
```

This could be optimized a bit with a worker-wrapper transform if desired.

**Comment by brandon-leapyear** [comment]
Yeah, I basically did that
```hs
foldConduit :: (i -> s -> ConduitT i o m s) -> s -> ConduitT i o m s
foldConduit f = go
  where
    go s = Conduit.await >>= \case
      Nothing -> return s
      Just i -> f i s >>= go
```
turns out to not be that bad, so I'm fine keeping it inline in my code. Off the top of your head, can you think of a better approach to solve my use case?

**Comment by snoyberg** [comment]
No other approach really jumps to mind, I don't think I've had to solve this kind of a problem before.

**Comment by brandon-leapyear** [comment]
Actually, I thought of this approach:
```hs
chunksByC :: ([a] -> Bool) -> ConduitT a [a] m ()
```
which would collate consecutive inputs as long as the predicate returned true. Does that seem useful enough to add to the library? If so, I can put up a PR. If not, I'll just implement inline and close the ticket

**Comment by snoyberg** [comment]
I don't think it's general enough for now.
