### ISSUE TITLE
Broken link to resourcet documentation

### ISSUE THREAD

**Issue by yitz-zoomin** [snoyberg/conduit#465]
The module haddock for `Control.Monad.Trans.Resource` says:

> For more information, see https://www.fpcomplete.com/user/snoyberg/library-documentation/resourcet

But that link is a 404.

**Comment by snoyberg** [comment]
I think you're looking at old versions of the docs.

**Comment by yitz-zoomin** [comment]
Very sorry, you're right.

No excuses, it way my fault. But I got there by clicking on a link to `ReleaseKey` from within the haddocks of the `temporary-resourcet` package, which (unfortunately) hasn't been updated for a few years.

Nowadays a lot of doc sites will give you a "not the latest" badge in cases like that. That would be a nice stackage/hackage feature.
