### ISSUE TITLE
Data.Conduit.Lift underneath ResourceT?

### ISSUE THREAD

**Issue by shlevy** [snoyberg/conduit#466]
I have a `ConduitT i o (ResourceT (ExceptT e IO)) r` and want to get a `ConduitT i o (ResourceT IO) (Either e r)`. Currently I am doing this with `transPipe` and `transResourceT` and rethrowing the error (which is an instance of `Exception`) with `throwIO`, but is there a way to do this with `Data.Conduit.Lift` or something similar?

**Comment by snoyberg** [comment]
There are ways to make it happen, but probably sticking with `transPipe` and `transResourceT` is good enough. "Ways to make it happen" would probably involve `withInternalState` and `runInternalState`, which is arguably just making it more complicated.

**Comment by shlevy** [comment]
OK, thanks!
