### ISSUE TITLE
What is ReleaseType for?

### ISSUE THREAD

**Issue by rightfold** [snoyberg/conduit#468]
I noticed that there is a data type called ReleaseType, which is passed to each finalizer stored in the release map.

But when registering a finalizer, it seems to be ignored (using `const`):

https://github.com/snoyberg/conduit/blob/1771780ff4b606296924a28bf5d4433ae6a916f3/resourcet/Control/Monad/Trans/Resource/Internal.hs#L312

I also couldn’t find any pattern matching on it.

I was wondering what the use for this data type is, as it seems to be always ignored.

**Comment by snoyberg** [comment]
It's used in newer parts of the API, e.g. https://www.stackage.org/haddock/nightly-2021-07-19/resourcet-1.2.4.2/Data-Acquire.html#v:mkAcquireType

**Comment by rightfold** [comment]
Ah I see! Thanks, that is very useful. :)
