### ISSUE TITLE
slidingWindowC makes consuming tail elements inconvenient

### ISSUE THREAD

**Issue by kaol** [snoyberg/conduit#472]
I could use a version of `slidingWindowC` that would give easier access to the tail elements.

```
yieldMany [1,2,3] .| slidingWindowC 2 .| sinkList
```
gives a `[[1,2],[2,3]]` but I'd like to have a version `slidingWindowTailsC` that would give `[[1,2],[2,3],[3]]`.

With `slidingWindowC` nothing tells me that `[2,3]` is the last element of the stream and it's hard to tell that I'd need to special case `3` in it.

For the general case, I think it would be sufficient to just add one extra element for `slidingWindosTailsC n` with `n-1` elements in it.

**Comment by snoyberg** [comment]
There's not really enough here to understand the request. But for this kind of case it sounds like a `ZipSink` usage with `lastC` may be relevant.

**Comment by kaol** [comment]
In the end I ended up writing this function:
```
slidingWindowWithTailC :: Monad m => Int -> ConduitT a [a] m ()
slidingWindowWithTailC sz = do
  xs <- slidingWindowC sz .| sinkList
  yieldMany xs
  when ((sz > 1) && (not $ null xs)) $
    yield $ tail $ last xs
```
It's not exactly pretty but it did the job for my case. I'll just close the issue, I'll leave it up to you to reopen it if this would seem useful in general.

**Comment by snoyberg** [comment]
Keep in mind that this will read all the elements into memory, losing any advantages of streaming the data.
