### ISSUE TITLE
Quadratic performance on left-associated binds

### ISSUE THREAD

**Issue by tomjaguarpaw** [snoyberg/conduit#474]
# EDIT: There is no bug in conduit

![image](https://user-images.githubusercontent.com/1951567/135747179-e5b0f0ab-1a62-470a-ac50-9e251c27f5e1.png)

----
Old mistaken report follows:

# The problem

Consider walking over a tree using a streaming library to do something at every leaf:

```haskell
data Tree = Branch Tree Tree | Leaf Int

walkTreeTransformer :: (Monad (m IO), MonadTrans m)
                    => (Int -> IO ()) -> Tree -> m IO ()
walkTreeTransformer doSomething = loop
  where loop = \case
          Leaf i -> lift (doSomething i)
          Branch t1 t2 -> do
            loop t1
            loop t2
```

On left-skewed trees, i.e. trees that will end up generating left-associated binds, for example those generated by `leftSkewed`

```haskell
-- Fully evaluated left-skewed tree
leftSkewed :: Int -> Tree
leftSkewed 0 = Leaf 0
leftSkewed n = (Branch $! leftSkewed (n - 1)) (Leaf n)
```

the performance of your streaming library is quadratic. In fact performance is quadratic under

* streaming: https://github.com/haskell-streaming/streaming/issues/109
* pipes: https://github.com/Gabriel439/Haskell-Pipes-Library/issues/234
* conduit

(The only streaming library I know of whose performance is not quadratic is streamly.)

The plot below demonstrates the claim. The code to generate the plot is available at https://github.com/tomjaguarpaw/streaming-benchmark. The compiler was GHC 8.10.7.

![image](https://user-images.githubusercontent.com/1951567/135711881-d7a1320f-ac2f-4d98-8a4c-c4e7f8bc447d.png)

# The solution

Firstly, before talking about a solution, do you actually consider this a bug? I do, and I think the risk of hitting unexpected quadratic performance makes this library unsuitable for production use as it is. On the other hand maybe you have a good reason that I shouldn't think that. If so I would be interested to hear it.

If you *do* think this is a bug then let's think about what can be done. I know of two straightforward options:

1. Add [an explicit constructor for binds](https://github.com/tomjaguarpaw/streaming-benchmark/blob/master/app/Streaming/Better.hs#L9-L12) and then [reassociate binds during elimination](https://github.com/tomjaguarpaw/streaming-benchmark/blob/master/app/Streaming/Better.hs#L49-L62)
2. Use [`Codensity`](https://github.com/tomjaguarpaw/streaming-benchmark/blob/master/app/Streaming/Codensity.hs#L9) (streamly essentially uses [handwritten `Codensity`](https://hackage.haskell.org/package/streamly-0.8.0/docs/src/Streamly.Internal.Data.Stream.StreamK.Type.html#Stream).)

In my benchmarks explicit bind comes out slightly ahead. (The examples are implemented to match `streaming` but the same techniques ought to apply to your library.)

Perhaps there is another option more suitable for your library.

I welcome your thoughts.

**Comment by snoyberg** [comment]
I'm interested in fixing this. However, the report surprises me, since the internal implementation of `ConduitT` is supposed to include a codensity transform. The [definition](https://www.stackage.org/haddock/nightly-2021-10-02/conduit-1.3.4.2/src/Data.Conduit.Internal.Conduit.html#ConduitT) is:

```haskell
newtype ConduitT i o m r = ConduitT
    { unConduitT :: forall b.
                    (r -> Pipe i i o () m b) -> Pipe i i o () m b
    }
```

In fact, with recent ~~breakages~~ changes in GHC, this has led to the need for changes. I'm wondering if the semantics of GHC have subtly changed recently to undo the codensity transform work and require something new. (Though I don't think those changes impacted GHC 8.10.)

**Comment by tomjaguarpaw** [comment]
Interesting. I can try on different versions of GHC.

**Comment by tomjaguarpaw** [comment]
Same problem on 8.6.5:

![image](https://user-images.githubusercontent.com/1951567/135746088-54aea21d-adea-4e2f-8bde-d32f310bcc7e.png)

**Comment by tomjaguarpaw** [comment]
Embarrassing mistake on my part. I was benchmarking pipes twice and calling it conduit by accident! I shall correct the record.

**Comment by tomjaguarpaw** [comment]
This is what I got wrong. Sorry for the distraction.

https://github.com/tomjaguarpaw/streaming-benchmark/commit/2a965a790c23c759c70ac580b25c59fd22ae922c#diff-d8eb1fcee93b2f8694c2b1cd2f93251beec34d134b00666be9c257c55a82fa56

**Comment by snoyberg** [comment]
Thanks for confirming! I looked at the code and saw the pipes comment, but assumed it was the internal Pipe data type. Good to know the codensity transform is still working as expected.
