### ISSUE TITLE
"stdout" test stalls temporarily sometimes

### ISSUE THREAD

**Issue by chrismwendt** [snoyberg/conduit#478]
When running the tests for `cabal`, I noticed it hangs 20% of the time on the `stdout` test:

https://github.com/snoyberg/conduit/blob/f371e828a41b4cdc5c57d0862a56ce176d5fcbbd/conduit/test/Spec.hs#L350-L353

```
$ stack test cabal
...
  sinkFile
  sinkHandle
  sinkIOHandle
  print
    +++ OK, passed 100 tests.
82/100 <--- stalls here
```

That `82/100` is coming from [where hspec prints test progress](https://github.com/hspec/hspec/blob/557cd17ce5b3aadc6cbe60ba4b0312c75f282d95/hspec-core/src/Test/Hspec/Core/Formatters/Internal.hs#L219-L224) which [prints asynchronously](https://github.com/hspec/hspec/blob/557cd17ce5b3aadc6cbe60ba4b0312c75f282d95/hspec-core/src/Test/Hspec/Core/Format.hs#L98) while looping through 100 examples generated by QuickCheck. The test sometimes captures output from a concurrent hspec stdout write and fails:

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/1387653/154864943-0860e821-5d47-42fd-b908-ffa81f18e2bd.png">

Although I couldn't repro by injecting failures, I think that because of QuickCheck's shrinking, it keeps trying to find an input that fails again after it hits a failure (it never will because progress won't be printed), and the memory usage skyrockets to over 26GB:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1387653/154864837-52827061-be36-4577-8ccc-0f470c5414f3.png">

After the test stopped or got killed, the total memory usage on my system dropped back down:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/1387653/154864844-3897f658-343c-4de7-99e0-90e6d421236c.png">

I captured a heap profile with `ghcoptions: -Wall -rtsopts -with-rtopts=-h`, and the memory rose (very slowly, I stopped it after a couple minutes):

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/1387653/154864337-c8b48a32-052f-4a7c-bc9a-76ed9eb1da8e.png">

Environment:

- Apple M1 macOS 12.0.1
- `stack --version` prints Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
- On commit f371e828a41b4cdc5c57d0862a56ce176d5fcbbd

**Comment by chrismwendt** [comment]
A workaround is to specify a different hspec formatter that doesn't print to stdout while the test is running, but it's unintuitive for the test passing to depend on which test framework formatter you're using.

Alternatively, the test could run in a subprocess so that it has a different stdout. That's a pretty heavyweight solution.

Another option is to put the test behind a flag like `--enable-stdout-tests` and default to disabled.

**Comment by snoyberg** [comment]
`stdoutC` is a thin wrapper around `sinkHandle`. It's probably best to simply skip this test and rely on tests of `sinkHandle` instead. I'd accept a PR for this. However, I've never experienced this behavior myself, and it may indicate that there are issues elsewhere. I don't think conduit is the culprit here.

**Comment by chrismwendt** [comment]
The timer ticks at [0.05s intervals](https://github.com/hspec/hspec/blob/557cd17ce5b3aadc6cbe60ba4b0312c75f282d95/hspec-core/src/Test/Hspec/Core/Runner/Eval.hs#L144), so slower machines are more likely to encounter the error (maybe yours is fast). It's moreso the conflicting uses of stdout between hspec and the conduit tests than one or the other individually that's causing this issue. PR pending.
