### ISSUE TITLE
*> leaks space where >> doesn't - so should the *> implementation be optimized?

### ISSUE THREAD

**Issue by alaendle** [snoyberg/conduit#496]
Basically an implementation like the following leaks space:
```haskell
source :: Monad m => [Int] -> ConduitT i Int m ()
source s = case s of
  [] -> pure ()
  n : ns -> yield n *> source ns
```
Switching to `>>` avoids the problem. That makes me believe that the implementation of `*>`could/should be optimized.

To be honest I don't fully understand what causes the different behavior (my assumption is that the applicative implementation isn't aware of the container and so the monad implementation takes shortcuts).

A (maybe dirty) hack to solve this problem is to just implement `*>` with `>>` by adding

```haskell
    (*>) = (>>)
    {-# INLINE (*>) #-}
```

to

https://github.com/snoyberg/conduit/blob/8020ac867a381f41fb85372d2e7791846f1a719a/conduit/src/Data/Conduit/Internal/Conduit.hs#L146-L150

(See https://stackoverflow.com/questions/73460640/haskell-based-file-streaming-causes-memory-leak for the original problem)

Please let me know if I was unclear or if I could provide further information. Also I'm willing to provide a PR (but need some guidance if a more sophisticated solution is required).

**Comment by snoyberg** [comment]
That description makes sense, and it's the kind of thing that pops up occasionally, especially due to the (now ancient) AMP (Application/Monad Proposal). Your proposed "dirty" hack is actually a perfect approach. Would you be up for opening a PR to make the change?
