### ISSUE TITLE
"The mutable state is being accessed after cleanup" exception

### ISSUE THREAD

**Issue by nikita-volkov** [snoyberg/conduit#85]
I have a concurrent program, which depending on some settings spits out: `Control.Monad.Trans.Resource.register': The mutable state is being accessed after cleanup. Please contact the maintainers.` 

I am highly unsure of where it's stemming from, and whether it's caused by my mistake or a bug of conduit or even by [this GHC bug](http://hackage.haskell.org/trac/ghc/ticket/7636) which the same program of mine suffers from in certain conditions.

Here is [a short screencast](http://screencast.com/t/jN10vAX7mF) describing the issue in detail. Could you please check it out?

**Comment by MaxGabriel** [comment]
> Performing a forkIO inside of a ResourceT is inherently unsafe; you need to use resourceForkIO instead. It looks to me like there's a bug in couchdb's usage of resourcet, but without inspecting that codebase I can't be certain.

We've run into this a few times at work. I wanted to confirm this advice is still true. If so, should it be documented somewhere? I couldn't find anything about this in the haddocks, but I may have been looking in the wrong place. I could PR it

**Comment by snoyberg** [comment]
I thought it was covered, but if not, or if you see places where the docs can be improved, a PR is definitely welcome.
